/*
 * HomeSynapse — Mock SCENARIOS (T1.2, the pre-hardware sprint keystone).
 * ---------------------------------------------------------------------------
 * A scenario system that can produce EVERY condition the FROZEN v1.1 contract allows, on
 * demand — so the mock demo is complete now, FE-4 can verify every state on realistic data,
 * and live-integration (FE-1) meets no shape it hasn't already faced. Every dataset is shaped
 * by the same contract types the real transport returns; contract.test.ts validates them.
 *
 * Two orthogonal dimensions (see mockState.ts): a DATA scenario (the story the data tells) and
 * a TRANSPORT condition (replaying / offline / slow / 401 / 403 / etag). This file owns the data.
 *
 * Bundle note: variant datasets are built lazily (`build()`), and large lists are GENERATED by
 * code (not materialized literals), so the static footprint stays small — mock ships in the
 * demo/website-embed builds (sprint §T1.2), and we keep the 100 KB budget honest.
 */
import type {
  AutomationSummary,
  CausalAction,
  CausalChain,
  CausalCondition,
  ConditionDefinition,
  ConsolidatedHealth,
  DlqStatus,
  EntityDetail,
  EntityState,
  EntitySummary,
  EventSummary,
  NonFiringExplanation,
  Origin,
  ProjectionStatus,
  RunStatus,
  ActionOutcome,
  NonFiringVerdict,
  RunSummary,
} from '../contract';
import * as base from './mockData';

/** The full fixture bundle a scenario serves. Mirrors the endpoints in mockTransport. */
export interface MockDataset {
  entities: EntitySummary[];
  entityDetail: Record<string, EntityDetail>;
  entityState: Record<string, EntityState>;
  projection: ProjectionStatus;
  dlq: DlqStatus;
  health: ConsolidatedHealth;
  automations: AutomationSummary[];
  runs: RunSummary[];
  causalChains: Record<string, CausalChain>;
  nonFiring: Record<string, NonFiringExplanation>;
  events: EventSummary[];
}

const now = Date.now();
const iso = (minAgo: number) => new Date(now - minAgo * 60_000).toISOString();
/** An instant `plusMs` after an ISO instant — the v1.1.4 settledAt / confirmedAt beside a trigger's matchedAt. */
const after = (isoAt: string, plusMs: number) => new Date(new Date(isoAt).getTime() + plusMs).toISOString();
/* FE-115 D2: the mock hub is a v1.1.5 hub — every factory carries the v1.1.4 / v1.1.5 keys PRESENT (a value
 * where the scenario has one, JSON null elsewhere; never absent), so the DevPanel reaches every arm FE-114 and
 * FE-115 render. `definitionKeyFor` is a deterministic 64-hex string of the DefinitionHashes SHAPE (a mock
 * value, not a hash of anything real — DP-5's equality between the automations / non-firing / chain reads holds
 * because the three reads derive it from the same seed). The `legacy-hub` scenario strips the keys again. */
function definitionKeyFor(seed: string): string {
  let h = 0x811c9dc5;
  let out = '';
  for (let round = 0; round < 8; round++) {
    for (let i = 0; i < seed.length; i++) {
      h ^= seed.charCodeAt(i) + round;
      h = Math.imul(h, 0x01000193) >>> 0;
    }
    out += h.toString(16).padStart(8, '0');
  }
  return out;
}
/** The v1.1.5 structured definition in the emitter's nine-key order (a leaf: children []). */
function def(type: string, o: Partial<Omit<ConditionDefinition, 'type' | 'children'>> = {}, children: ConditionDefinition[] = []): ConditionDefinition {
  return {
    type,
    selector: o.selector ?? null,
    attribute: o.attribute ?? null,
    value: o.value ?? null,
    above: o.above ?? null,
    below: o.below ?? null,
    after: o.after ?? null,
    before: o.before ?? null,
    children,
  };
}
/** The default condition's definition — what "time is after sunset" is on the wire: the sun's elevation below 0. */
const AFTER_SUNSET_DEF = (): ConditionDefinition => def('NumericCondition', { selector: 'sys_sun', attribute: 'elevation', below: 0 });
let evSeq = 90_000;
const nextEvVp = () => ++evSeq;

/* ---- Contract-shaped factories (defaults + overrides; keep every field on-contract) ---- */

const ACTION_REASON: Record<ActionOutcome, string | null> = {
  CONFIRMED: null,
  DISPATCHED: null,
  UNCONFIRMED: 'No state_confirmed within the 5s timeout',
  FAILED: 'Device unreachable — the command was rejected',
  SKIPPED: 'A condition was not met',
};

/* [MOCK — pending the SKIP-VIS DEPLOY] The ruled v1.1.2 additive keys, defaulted
 * per outcome class (law (c): mock to the RULED shape, never beyond it):
 *   resultOutcome = the raw command_result.outcome backing the derivation (null
 *   when no command_result exists — e.g. a bare dispatch or a confirmation
 *   timeout); settled = the Q1b rule (false exactly for a DISPATCHED action with
 *   no settling record). Scenarios that reproduce the PRE-v1.1.2 deployed wire
 *   pass `resultOutcome: undefined, settled: undefined` to strip the keys. */
const ACTION_RESULT_OUTCOME: Record<ActionOutcome, string | null> = {
  // HERO-1b B7: null, not 'acknowledged' — the zigbee handler publishes command_result only
  // on failure, so a device-confirmed command lawfully carries NO verdict row (F-R4b-H); the
  // always-populated value was the H8 false-VALUE class (contract-consumer.md §5).
  CONFIRMED: null,
  DISPATCHED: null,
  UNCONFIRMED: null,
  FAILED: 'rejected',
  SKIPPED: null,
};

function makeAction(outcome: ActionOutcome, over: Partial<CausalAction> = {}): CausalAction {
  const a: CausalAction = {
    type: 'device_command',
    targetRef: { type: 'ENTITY', id: 'ent_hallway_light' },
    command: 'turn_on',
    params: outcome === 'SKIPPED' ? {} : { brightness: 82 },
    outcome,
    reason: ACTION_REASON[outcome],
    resultOutcome: ACTION_RESULT_OUTCOME[outcome],
    settled: outcome !== 'DISPATCHED',
    ...over,
  };
  // An explicit `undefined` override means "this payload predates v1.1.2" —
  // strip the key entirely so validators see a true pre-v1.1.2 shape.
  if (a.resultOutcome === undefined) delete a.resultOutcome;
  if (a.settled === undefined) delete a.settled;
  return a;
}

function makeCondition(result: boolean, over: Partial<CausalCondition> = {}): CausalCondition {
  const c: CausalCondition = {
    expression: 'time is after sunset',
    evaluated: true,
    result,
    observedState: [{ entityId: 'sys_sun', attribute: 'elevation', value: result ? '-6.2°' : '+24.7°' }],
    // v1.1.5 (FE-115 D2): PRESENT on every condition — the structured definition, or null when a scenario says so.
    definition: AFTER_SUNSET_DEF(),
    ...over,
  };
  // An explicit `undefined` override means "this payload predates v1.1.5" — strip the key entirely.
  if (c.definition === undefined) delete c.definition;
  return c;
}

interface ChainOpts {
  automationId?: string;
  automationName?: string;
  outcome?: ActionOutcome;
  status?: RunStatus;
  conditionResult?: boolean;
  parentRunId?: string | null;
  depth?: number;
  triggerId?: string;
  targetId?: string;
  terminalReason?: string | null;
  durationMs?: number;
  minAgo?: number;
  /** Exact trigger time (overrides minAgo) — for scenarios anchored to build time. */
  matchedAtIso?: string;
  /** Full actions override (e.g. the E5 multi-action / live-flip chains). */
  actions?: CausalAction[];
  /** A chain from a hub that predates v1.1.4 / v1.1.5 (the verdict-vocabulary scenario): no definitionKey, no
   *  condition definition, no settledAt / confirmedAt. Default false — the mock hub is a v1.1.5 hub. */
  legacy?: boolean;
  /** The chain's v1.1.4 definitionKey; `null` = the log carries none (the prior-instance class). */
  definitionKey?: string | null;
}

function makeChain(runId: string, o: ChainOpts = {}): CausalChain {
  const status = o.status ?? 'COMPLETED';
  const outcome = o.outcome ?? (status === 'SKIPPED' ? 'SKIPPED' : 'CONFIRMED');
  const condResult = o.conditionResult ?? status !== 'SKIPPED';
  const matchedAt = o.matchedAtIso ?? iso(o.minAgo ?? 2);
  const durationMs = o.durationMs ?? 412;
  const actions = (o.actions ?? [makeAction(outcome, { targetRef: { type: 'ENTITY', id: o.targetId ?? 'ent_hallway_light' } })]).map((a) =>
    o.legacy ? a : withV114Instants(a, matchedAt, durationMs),
  );
  const automationId = o.automationId ?? 'auto_demo';
  const chain: CausalChain = {
    runId,
    automationId,
    automationName: o.automationName ?? 'Demo automation',
    trigger: {
      type: 'state_changed',
      subjectRef: { type: 'ENTITY', id: o.triggerId ?? 'ent_hallway_motion' },
      matchedAt,
      firingValue: 'motion = detected',
    },
    conditions: [makeCondition(condResult, o.legacy ? { definition: undefined } : {})],
    actions,
    outcome: {
      status,
      reason: o.terminalReason ?? null,
      durationMs,
      actionCount: actions.length,
      commandCount: actions.filter((a) => a.outcome !== 'SKIPPED').length,
    },
    cascade: { parentRunId: o.parentRunId ?? null, depth: o.depth ?? 0 },
  };
  // v1.1.4 (FE-115 D2): definitionKey PRESENT (appended after cascade — the wire order), the same seed the
  // automations / non-firing reads use for this automation (DP-5); null when a scenario says the log carries none.
  if (!o.legacy) chain.definitionKey = o.definitionKey === undefined ? definitionKeyFor(automationId) : o.definitionKey;
  return chain;
}

/** v1.1.4 (FE-115 D2): settledAt / confirmedAt PRESENT on a v1.1.2-shaped action that does not already carry
 *  them, derived from the mode the emitter would have classified: a bare DISPATCHED (unsettled) → both null; a
 *  CONFIRMED → both the confirmation instant; any other settled outcome → settledAt the classifying instant,
 *  confirmedAt null (`settled: true` beside `confirmedAt: null` — the lawful pair). A pre-v1.1.2 action (no
 *  resultOutcome key) is left as it is — a hub that old carries no v1.1.4 key either. */
function withV114Instants(a: CausalAction, matchedAt: string, durationMs: number): CausalAction {
  if (!('resultOutcome' in a)) return a;
  if ('settledAt' in a && 'confirmedAt' in a) return a;
  const settled = a.settled !== false;
  const classifyingAt = after(matchedAt, Math.max(50, Math.min(durationMs, 60_000) - 30));
  // Added IN PLACE (never spread): a scenario's live-flipping action defines its fields as getters
  // (e5-confirmation), and a copy would freeze them at build time.
  if (!('settledAt' in a)) a.settledAt = settled ? classifyingAt : null;
  if (!('confirmedAt' in a)) a.confirmedAt = a.outcome === 'CONFIRMED' ? classifyingAt : null;
  return a;
}

function makeRun(runId: string, o: Partial<RunSummary> & { minAgo?: number } = {}): RunSummary {
  return {
    runId,
    automationId: o.automationId ?? 'auto_demo',
    automationName: o.automationName ?? 'Demo automation',
    triggeredAt: o.triggeredAt ?? iso(o.minAgo ?? 2),
    status: o.status ?? 'COMPLETED',
    terminalReason: o.terminalReason ?? null,
  };
}

function makeEvent(eventId: string, origin: Origin, over: Partial<EventSummary> = {}): EventSummary {
  const SUMMARY: Record<Origin, string> = {
    AUTOMATION: 'Hallway Light turned on',
    DEVICE: 'Hallway Motion detected motion',
    USER: 'Living Room Lamp turned off from the app',
    EXTERNAL: 'Kitchen Light changed outside the system',
    UNKNOWN: 'Kitchen Light reported a brightness change',
  };
  return {
    eventId,
    type: 'state_changed',
    category: 'STATE',
    occurredAt: iso(1),
    viewPosition: nextEvVp(),
    subjectRef: { type: 'ENTITY', id: 'ent_hallway_light' },
    correlationId: 'cor_demo',
    causationId: null,
    origin,
    summary: SUMMARY[origin],
    ...over,
  };
}

function makeNonFiring(
  automationId: string,
  verdict: NonFiringVerdict,
  over: Partial<NonFiringExplanation> = {},
): NonFiringExplanation {
  const EXPLAIN: Record<NonFiringVerdict, string> = {
    CONDITION_NOT_MET: 'It did not run because it was before sunset when the trigger fired.',
    NEVER_TRIGGERED: 'Nothing set it off. The trigger has not matched in the last hour.',
    ACTED_BUT_UNCONFIRMED: 'It ran, but the device never confirmed it acted — it may be slow or briefly offline.',
    DISABLED: 'This automation is turned off, so it cannot run.',
    // FE-114 D0 (type-forced by the v1.1.4 verdict union; no scenario constructs it yet — the next mock
    // touch): the wire's own sentence shape for the clean-confirmed case; the dashboard renders no
    // `explanation` string (SPEC §2 gives it no slot).
    FIRED_CONFIRMED: 'It last fired and its device confirmed; no non-firing was detected in the requested window.',
  };
  const nf: NonFiringExplanation = {
    automationId,
    automationName: over.automationName ?? 'Demo automation',
    enabled: verdict !== 'DISABLED',
    verdict,
    // v1.1.4: FIRED_CONFIRMED always carries its run id (the rest-api table); NEVER_TRIGGERED never does.
    lastRelevantRunId: verdict === 'CONDITION_NOT_MET' || verdict === 'ACTED_BUT_UNCONFIRMED' || verdict === 'FIRED_CONFIRMED' ? 'run_demo_ref' : null,
    explanation: EXPLAIN[verdict],
    triggerSummary: 'This runs when Hallway Motion detects motion, after sunset.',
    // OBSERVED LIVE SHAPE (2026-08-16, §4.5): the wire nulls the WHOLE object
    // when there is no evaluation on record — the scenario fleet carries the
    // real tri-state (object with values · whole-object null), not the
    // always-populated shape that manufactured DX-16's false type.
    lastEvaluation:
      verdict === 'CONDITION_NOT_MET'
        ? { at: iso(30), conditionsResult: 'after sunset = false' }
        : null,
    // v1.1.2 (SKIP-VIS DP-2): null on every non-silent-skip construction
    // (never false); the silent-skip case overrides with true.
    noCommandsIssued: null,
    // v1.1.4 (FE-115 D2): PRESENT in the wire order after triggerRef — the auto-disable marker's instant and
    // reason on the DISABLED verdict ("configuration" = DISABLED with no marker on the log, DP-6 — the default
    // here carries the marker), null on every other verdict; definitionKey never null (the registry answered).
    disabledAt: verdict === 'DISABLED' ? iso(180) : null,
    disabledReason: verdict === 'DISABLED' ? 'repeated_failure' : null,
    definitionKey: definitionKeyFor(automationId),
    ...over,
  };
  if (nf.noCommandsIssued === undefined) delete nf.noCommandsIssued;
  if (nf.disabledAt === undefined) delete nf.disabledAt;
  if (nf.disabledReason === undefined) delete nf.disabledReason;
  if (nf.definitionKey === undefined) delete nf.definitionKey;
  return nf;
}

function makeAutomation(automationId: string, name: string, over: Partial<AutomationSummary> = {}): AutomationSummary {
  return {
    automationId,
    name,
    enabled: true,
    components: [
      { type: 'trigger', summary: 'When Hallway Motion detects motion' },
      { type: 'condition', summary: 'Only after sunset' },
      { type: 'action', summary: 'Turn on Hallway Light' },
    ],
    lastRunId: null,
    // v1.1.4 (FE-115 D2): PRESENT after lastRunId; the same seed as the chain / non-firing reads (DP-5).
    definitionKey: definitionKeyFor(automationId),
    ...over,
  };
}

/* ---- The default coherent home (the current fixtures) ---- */
export const defaultDataset: MockDataset = {
  entities: base.entities,
  entityDetail: base.entityDetail,
  entityState: base.entityState,
  projection: base.projection,
  dlq: base.dlq,
  health: base.health,
  automations: base.automations,
  runs: base.runs,
  causalChains: base.causalChains,
  nonFiring: base.nonFiring,
  events: base.events,
};

/* ---- Variant builders ---- */

// Every command outcome + every run status, one automation, as a run list you can click through.
function buildAllOutcomes(): MockDataset {
  const A = { automationId: 'auto_demo', automationName: 'Demo automation' };
  const specs: { id: string; outcome: ActionOutcome; status: RunStatus; reason?: string | null; min: number }[] = [
    { id: 'run_oc_confirmed', outcome: 'CONFIRMED', status: 'COMPLETED', min: 2 },
    { id: 'run_oc_dispatched', outcome: 'DISPATCHED', status: 'COMPLETED', reason: 'Command sent; awaiting confirmation', min: 4 },
    { id: 'run_oc_unconfirmed', outcome: 'UNCONFIRMED', status: 'COMPLETED', reason: 'Action sent; device did not confirm within 5s', min: 9 },
    { id: 'run_oc_failed', outcome: 'FAILED', status: 'FAILED', reason: 'Device unreachable', min: 22 },
    { id: 'run_oc_skipped', outcome: 'SKIPPED', status: 'SKIPPED', reason: 'Condition not met: before sunset', min: 40 },
    { id: 'run_oc_cancelled', outcome: 'SKIPPED', status: 'CANCELLED', reason: 'Superseded by a newer run', min: 70 },
    { id: 'run_oc_interrupted', outcome: 'FAILED', status: 'INTERRUPTED', reason: 'System restarted mid-run', min: 130 },
  ];
  const runs = specs.map((s) => makeRun(s.id, { ...A, status: s.status, terminalReason: s.reason ?? null, minAgo: s.min }));
  const causalChains: Record<string, CausalChain> = {};
  for (const s of specs) {
    causalChains[s.id] = makeChain(s.id, {
      ...A,
      outcome: s.outcome,
      status: s.status,
      conditionResult: s.status !== 'SKIPPED',
      terminalReason: s.reason ?? null,
      minAgo: s.min,
    });
  }
  return {
    ...defaultDataset,
    automations: [makeAutomation('auto_demo', 'Demo automation', { lastRunId: 'run_oc_confirmed' })],
    runs,
    causalChains,
    nonFiring: { auto_demo: makeNonFiring('auto_demo', 'NEVER_TRIGGERED', { automationName: 'Demo automation' }) },
  };
}

// A parent → child cascade: one run triggers another; the child links back to its cause.
function buildCascade(): MockDataset {
  const parent = makeChain('run_casc_parent', {
    automationId: 'auto_sunset',
    automationName: 'Sunset Scene',
    triggerId: 'sys_sun',
    targetId: 'ent_livingroom_lamp',
    minAgo: 3,
  });
  parent.trigger = { type: 'time', subjectRef: { type: 'SYSTEM', id: 'sys_sun' }, matchedAt: iso(3), firingValue: 'sun set' };
  const child = makeChain('run_casc_child', {
    automationId: 'auto_evening_hallway',
    automationName: 'Evening Hallway Light',
    parentRunId: 'run_casc_parent',
    depth: 1,
    minAgo: 3,
  });
  return {
    ...defaultDataset,
    automations: [
      makeAutomation('auto_sunset', 'Sunset Scene', { lastRunId: 'run_casc_parent' }),
      makeAutomation('auto_evening_hallway', 'Evening Hallway Light', { lastRunId: 'run_casc_child' }),
    ],
    runs: [
      makeRun('run_casc_child', { automationId: 'auto_evening_hallway', automationName: 'Evening Hallway Light', minAgo: 3 }),
      makeRun('run_casc_parent', { automationId: 'auto_sunset', automationName: 'Sunset Scene', minAgo: 3 }),
    ],
    causalChains: { run_casc_parent: parent, run_casc_child: child },
  };
}

// All four "why didn't it fire?" verdicts, one automation each.
function buildAllVerdicts(): MockDataset {
  const defs: { id: string; name: string; verdict: NonFiringVerdict }[] = [
    { id: 'auto_v_condition', name: 'Front Door Welcome', verdict: 'CONDITION_NOT_MET' },
    { id: 'auto_v_never', name: 'Evening Hallway Light', verdict: 'NEVER_TRIGGERED' },
    { id: 'auto_v_acted', name: 'Bedtime Lights Off', verdict: 'ACTED_BUT_UNCONFIRMED' },
    { id: 'auto_v_disabled', name: 'Bedroom Night Light', verdict: 'DISABLED' },
  ];
  const nonFiring: Record<string, NonFiringExplanation> = {};
  for (const d of defs) nonFiring[d.id] = makeNonFiring(d.id, d.verdict, { automationName: d.name });
  return {
    ...defaultDataset,
    automations: defs.map((d) => makeAutomation(d.id, d.name, { enabled: d.verdict !== 'DISABLED' })),
    nonFiring,
  };
}

// Every event origin, including the honest UNKNOWN (never a silent blank).
function buildAllOrigins(): MockDataset {
  const origins: Origin[] = ['AUTOMATION', 'DEVICE', 'USER', 'EXTERNAL', 'UNKNOWN'];
  return {
    ...defaultDataset,
    events: origins.map((o, i) => makeEvent(`evt_origin_${i}`, o, { occurredAt: iso(i + 1) })),
  };
}

// Hundreds of rows — the input that forces list virtualization (T2.3) and stresses render-at-scale.
function buildLarge(): MockDataset {
  const STATUSES: RunStatus[] = ['COMPLETED', 'FAILED', 'SKIPPED', 'CANCELLED', 'INTERRUPTED'];
  const OUTCOMES: ActionOutcome[] = ['CONFIRMED', 'DISPATCHED', 'UNCONFIRMED', 'FAILED', 'SKIPPED'];
  const ORIGINS: Origin[] = ['AUTOMATION', 'DEVICE', 'USER', 'EXTERNAL', 'UNKNOWN'];
  const runs: RunSummary[] = [];
  const causalChains: Record<string, CausalChain> = {};
  for (let i = 0; i < 300; i++) {
    const id = `run_lg_${String(i).padStart(4, '0')}`;
    const status = STATUSES[i % STATUSES.length]!;
    const outcome = OUTCOMES[i % OUTCOMES.length]!;
    runs.push(makeRun(id, { status, minAgo: i * 7 + 2, terminalReason: status === 'COMPLETED' ? null : `${status.toLowerCase()} (#${i})` }));
    causalChains[id] = makeChain(id, { outcome, status, minAgo: i * 7 + 2 });
  }
  const events: EventSummary[] = [];
  for (let i = 0; i < 500; i++) {
    events.push(makeEvent(`evt_lg_${String(i).padStart(4, '0')}`, ORIGINS[i % ORIGINS.length]!, { occurredAt: iso(i + 1) }));
  }
  return { ...defaultDataset, automations: [makeAutomation('auto_demo', 'Demo automation')], runs, causalChains, events };
}

/* The four MEASURED confirmation-rendering semantics (AMD-97, ratified 2026-07-01; measured
 * truth: nexsys-bench/corpus/devices/philips-hue-white-a19.md). Each behavior is one click:
 *  1. run_e5_ct         — color confirms SLOWLY and legitimately: DISPATCHED flips to CONFIRMED
 *                         ~8.4s after scenario activation (the measured upper command→report
 *                         sample), rendered live by the poll. Calm pending inside the window.
 *  2. run_e5_idempotent — no-change ⇒ no report: the backend confirms from cache/readback and
 *                         SAYS so; the UI renders the honest terminal state, never a spinner.
 *  3. run_e5_effect     — identify/effect class: acknowledged but never reported ⇒ honest
 *                         UNCONFIRMED immediately (an ACK is not confirmation).
 *  4. run_e5_superseded — rapid re-command coalesces reporting: the older expectation EXPIRES
 *                         (honest unconfirmed, never false-fail/false-confirm); no stale chip.
 * The timing values live in the corpus + Doc 08 §3.6 — the UI itself runs NO timeout; only
 * this mock (standing in for Core's confirmation engine) knows the window.
 */
function buildE5Confirmation(): MockDataset {
  const t0 = Date.now(); // scenario-activation anchor (NOT the module-load `now`)
  const at = (msAgo: number) => new Date(t0 - msAgo).toISOString();
  const CT_CONFIRM_MS = 8_400; // measured upper bound: 447-mired command→report 20:23:40.575→:48.999

  const lamp = { type: 'ENTITY', id: 'ent_livingroom_lamp' };
  const confirmed = () => Date.now() - t0 >= CT_CONFIRM_MS;

  // 1 — the live-flipping CT action (getters re-evaluate on every poll read).
  // v1.1.2: while DISPATCHED it is a bare in-flight action (resultOutcome null,
  // settled false — renders visibly PROVISIONAL); the flip settles it.
  const ctAction: CausalAction = {
    type: 'device_command',
    targetRef: lamp,
    command: 'set_color_temperature',
    params: { color_temp_kelvin: 2700 },
    get outcome(): ActionOutcome {
      return confirmed() ? 'CONFIRMED' : 'DISPATCHED';
    },
    get reason(): string | null {
      return confirmed() ? 'The device reported the new color temperature.' : null;
    },
    get resultOutcome(): string | null {
      return confirmed() ? 'acknowledged' : null;
    },
    get settled(): boolean {
      return confirmed();
    },
    // v1.1.4 (FE-115 D2): the instants flip WITH the outcome — null while a bare DISPATCHED (no classifying
    // event yet), the confirmation instant once the device reports (EXPLAIN-9's sentence appears live).
    get settledAt(): string | null {
      return confirmed() ? new Date(t0 + CT_CONFIRM_MS).toISOString() : null;
    },
    get confirmedAt(): string | null {
      return confirmed() ? new Date(t0 + CT_CONFIRM_MS).toISOString() : null;
    },
  };

  const chains: Record<string, CausalChain> = {
    run_e5_ct: makeChain('run_e5_ct', {
      automationId: 'auto_e5',
      automationName: 'Evening Color Scene',
      matchedAtIso: at(1_000),
      actions: [ctAction],
      durationMs: 240,
    }),
    run_e5_idempotent: makeChain('run_e5_idempotent', {
      automationId: 'auto_e5',
      automationName: 'Evening Color Scene',
      matchedAtIso: at(40_000),
      actions: [
        makeAction('CONFIRMED', {
          targetRef: lamp,
          command: 'turn_on',
          params: {},
          reason: 'Already on — confirmed from the device’s current state (no change to report).',
        }),
      ],
      durationMs: 180,
    }),
    run_e5_effect: makeChain('run_e5_effect', {
      automationId: 'auto_e5',
      automationName: 'Evening Color Scene',
      matchedAtIso: at(90_000),
      actions: [
        makeAction('UNCONFIRMED', {
          targetRef: lamp,
          command: 'identify',
          params: {},
          reason: 'The device acknowledged this command but never reports performing it.',
          // The acked-then-silent class on the ruled wire: honest-"unconfirmed".
          resultOutcome: 'unconfirmed',
        }),
      ],
      durationMs: 150,
    }),
    run_e5_superseded: makeChain('run_e5_superseded', {
      automationId: 'auto_e5',
      automationName: 'Evening Color Scene',
      matchedAtIso: at(150_000),
      actions: [
        makeAction('UNCONFIRMED', {
          targetRef: lamp,
          command: 'set_color_temperature',
          params: { color_temp_kelvin: 3500 },
          reason: 'Superseded — a newer color command replaced this one before the device reported.',
          // Mode 2's timed-out variant on the ruled wire: the supersession rides
          // resultOutcome; an intent change, never a failure.
          resultOutcome: 'superseded',
        }),
        makeAction('CONFIRMED', {
          targetRef: lamp,
          command: 'set_color_temperature',
          params: { color_temp_kelvin: 2200 },
          reason: null,
        }),
      ],
      durationMs: 620,
    }),
  };

  const runSpecs: { id: string; msAgo: number }[] = [
    { id: 'run_e5_ct', msAgo: 1_000 },
    { id: 'run_e5_idempotent', msAgo: 40_000 },
    { id: 'run_e5_effect', msAgo: 90_000 },
    { id: 'run_e5_superseded', msAgo: 150_000 },
  ];

  return {
    ...defaultDataset,
    automations: [makeAutomation('auto_e5', 'Evening Color Scene', { lastRunId: 'run_e5_ct' })],
    runs: runSpecs.map((r) =>
      makeRun(r.id, {
        automationId: 'auto_e5',
        automationName: 'Evening Color Scene',
        triggeredAt: at(r.msAgo),
        status: 'COMPLETED',
      }),
    ),
    causalChains: chains,
    nonFiring: { auto_e5: makeNonFiring('auto_e5', 'NEVER_TRIGGERED', { automationName: 'Evening Color Scene' }) },
  };
}

/* The TEN-value command_result vocabulary as the PRE-v1.1.2 DEPLOYED wire serves
 * it (the graceful-degrade exhibit): the pre-SKIP-VIS explanation service
 * flattens every non-acknowledged result into outcome:FAILED, with the truth
 * surviving only in the RECORDED REASON. This scenario reproduces that wire
 * faithfully — the two deterministic ledger disposition strings verbatim
 * (StandardPendingCommandLedger.java:912-916 / :922-924), bare outcome tokens
 * for the rest, and NO v1.1.2 keys (stripped) — so the recorded-reason recovery
 * path (the pre-v1.1.2 fallback that D-4's retirement keeps ONLY for payloads
 * like these) stays exercised against wire truth until the deploy completes.
 * The ruled v1.1.2 wire is the `five-modes` scenario.
 */
function buildVerdictVocabulary(): MockDataset {
  const A = { automationId: 'auto_vv', automationName: 'Verdict vocabulary' };
  const PRE_V112 = { resultOutcome: undefined, settled: undefined } as const;
  // [outcome-on-the-wire, recorded reason (wire-faithful), minutes ago]
  const flattened: { id: string; reason: string; min: number }[] = [
    {
      id: 'run_vv_superseded',
      reason:
        'superseded by a newer command on the same attribute; superseding command event 01JVVDEMO0000000000000000',
      min: 4,
    },
    { id: 'run_vv_expired', reason: 'command was in-flight at restart and is not idempotent', min: 8 },
    { id: 'run_vv_rejected', reason: 'rejected', min: 12 },
    { id: 'run_vv_timed_out', reason: 'timed_out', min: 16 },
    { id: 'run_vv_invalid', reason: 'invalid', min: 20 },
    { id: 'run_vv_unsupported', reason: 'unsupported', min: 24 },
    { id: 'run_vv_handler_error', reason: 'handler_error', min: 28 },
    { id: 'run_vv_integration', reason: 'integration_unavailable', min: 32 },
    { id: 'run_vv_unconfirmed', reason: 'unconfirmed', min: 36 },
  ];
  const runs: RunSummary[] = [];
  const causalChains: Record<string, CausalChain> = {};
  // The confirmed baseline (acknowledged → state_confirmed → CONFIRMED).
  runs.push(makeRun('run_vv_confirmed', { ...A, minAgo: 2 }));
  causalChains['run_vv_confirmed'] = makeChain('run_vv_confirmed', {
    ...A,
    legacy: true, // FE-115 D2: a pre-v1.1.2 wire carries no v1.1.4 / v1.1.5 key either
    minAgo: 2,
    actions: [makeAction('CONFIRMED', { ...PRE_V112 })],
  });
  for (const f of flattened) {
    runs.push(makeRun(f.id, { ...A, status: 'COMPLETED', minAgo: f.min }));
    causalChains[f.id] = makeChain(f.id, {
      ...A,
      legacy: true,
      status: 'COMPLETED',
      minAgo: f.min,
      actions: [makeAction('FAILED', { reason: f.reason, ...PRE_V112 })],
    });
  }
  return {
    ...defaultDataset,
    automations: [makeAutomation('auto_vv', 'Verdict vocabulary', { lastRunId: 'run_vv_confirmed' })],
    runs,
    causalChains,
    nonFiring: { auto_vv: makeNonFiring('auto_vv', 'NEVER_TRIGGERED', { automationName: 'Verdict vocabulary' }) },
  };
}

/* The field-evidence set (skill v1.4 §4c — every class observed on the certified
 * deployed build), one scenario:
 *   - the SILENT-SKIP run: COMPLETED, actionCount 2 / commandCount 0 / actions[]
 *     empty (lawful Doc 07 §3.9 per-target skips) — must never read as success;
 *   - the NULL-NAME run: automationName/trigger.type null (prior-instance runs);
 *   - the REHYDRATED-AVAILABLE entity: API says AVAILABLE from rehydrated history
 *     while the last evidence is days old (why the surface renders evidence-with-age);
 *   - the HONEST-UNKNOWN entity: no report since restart (calm, resolves on first report);
 *   - DP-B2 "ran fine": NEVER_TRIGGERED + non-null lastRelevantRunId pointing at
 *     the silent-skip run — the composed lie the run page then untangles honestly.
 */
function buildFieldEvidence(): MockDataset {
  // Silent-skip run — the actionCount-vs-actions[] disagreement IS the tell.
  const skip = makeChain('run_fe_skip', {
    automationId: 'auto_fe',
    automationName: 'Away lights',
    minAgo: 12,
  });
  skip.actions = [];
  skip.outcome = { status: 'COMPLETED', reason: null, durationMs: 41, actionCount: 2, commandCount: 0 };

  // Null-name run (prior-instance class): name + trigger.type null ON THE WIRE.
  const nullName = makeChain('run_fe_nullname', { minAgo: 2880 });
  nullName.automationName = null;
  nullName.trigger.type = null;
  const nullNameRun = makeRun('run_fe_nullname', { minAgo: 2880 });
  nullNameRun.automationName = null;

  const entities: EntitySummary[] = [
    ...base.entities,
    // Physically off-network, yet AVAILABLE from rehydrated history (AVAIL-RECONCILE).
    { entityId: 'ent_office_bulb', availability: 'AVAILABLE', stale: true },
    // Honest UNKNOWN since restart — no fresh report yet.
    { entityId: 'ent_porch_contact', availability: 'UNKNOWN', stale: false },
  ];
  const entityState: Record<string, EntityState> = {
    ...base.entityState,
    ent_office_bulb: {
      entityId: 'ent_office_bulb',
      availability: 'AVAILABLE',
      attributes: { power: { t: 'BOOL', v: true } },
      stateVersion: 44,
      lastChanged: iso(2760),
      lastUpdated: iso(2760),
      lastReported: iso(2760), // ~2 days of silence behind an "Available" flag
      stale: true,
      staleAfter: iso(2640),
    },
    ent_porch_contact: {
      entityId: 'ent_porch_contact',
      availability: 'UNKNOWN',
      attributes: {},
      stateVersion: 1,
      lastChanged: null,
      lastUpdated: null,
      lastReported: null,
      stale: false,
      staleAfter: null,
    },
  };

  return {
    ...defaultDataset,
    entities,
    entityState,
    automations: [makeAutomation('auto_fe', 'Away lights', { lastRunId: 'run_fe_skip' })],
    runs: [makeRun('run_fe_skip', { automationId: 'auto_fe', automationName: 'Away lights', minAgo: 12 }), nullNameRun],
    causalChains: { run_fe_skip: skip, run_fe_nullname: nullName },
    nonFiring: {
      // v1.1.2 (SKIP-VIS DP-2, LANDED core-side — MOCK pending the deploy): the
      // silent-skip run now reports ACTED_BUT_UNCONFIRMED with the
      // noCommandsIssued marker and the frozen "issued no device commands"
      // sentence — the clean-success "fired and confirmed" text is UNREACHABLE
      // on this path. (The pre-fix DP-B2 "ran fine" composed case this scenario
      // used to exhibit is retired with the landing.)
      auto_fe: makeNonFiring('auto_fe', 'ACTED_BUT_UNCONFIRMED', {
        automationName: 'Away lights',
        lastRelevantRunId: 'run_fe_skip',
        explanation:
          "Automation 'Away lights' fired, but issued no device commands — its device actions were skipped or issued nothing (targets unavailable or no device actions defined).",
        lastEvaluation: { at: iso(12), conditionsResult: 'true' },
        noCommandsIssued: true,
      }),
    },
  };
}

/* THE FIVE HONEST FAILURE MODES — the ruled v1.1.2 wire, pairwise-distinct on
 * (outcome, resultOutcome, reason) exactly as the core pins them
 * (explainRun_fiveFailureModesDistinct, SKIP-VIS DP-1) and as the Rosonway §5.1
 * exhibit showed them on silicon: five commands into a lamp that is not there,
 * and not one returned CONFIRMED. One chain, six actions (a confirmed baseline
 * + the five modes, each seeded to its PRIMARY table row):
 *   1. dispatched-and-timed-out      UNCONFIRMED / null          / "confirmation timed out"
 *   2. superseded-same-attribute     DISPATCHED  / "superseded"  / null
 *   3. acked-then-silent-forever     UNCONFIRMED / "unconfirmed" / the recorded zigbee reason VERBATIM
 *   4. held-DISPATCHED               DISPATCHED  / null          / null            (settled:false — PROVISIONAL)
 *   5. settled-FAILED                FAILED      / "rejected"    / "device offline"
 * [MOCK — pending the SKIP-VIS DEPLOY; law (c): mocked to the RULED shape.]
 * The run's triggeredAt ≡ trigger.matchedAt exactly (the DP-3 VALUE correction,
 * pinned here so the mock carries the corrected value semantics).
 */
function buildFiveModes(): MockDataset {
  const A = { automationId: 'auto_fm', automationName: 'Evening lamp scene' };
  const lamp = { type: 'ENTITY', id: 'ent_livingroom_lamp' };
  const matched = iso(6);
  const chain = makeChain('run_fm_all', {
    ...A,
    matchedAtIso: matched,
    durationMs: 34204,
    actions: [
      makeAction('CONFIRMED', { targetRef: lamp, command: 'turn_on', params: {} }),
      makeAction('UNCONFIRMED', {
        targetRef: lamp,
        command: 'set_brightness',
        params: { brightness: 50 },
        reason: 'confirmation timed out',
      }),
      makeAction('DISPATCHED', {
        targetRef: lamp,
        command: 'set_color_temp',
        params: { color_temp_kelvin: 4550 },
        reason: null,
        resultOutcome: 'superseded',
        settled: true, // a superseded DISPATCHED is settled — the ledger dropped it
      }),
      makeAction('UNCONFIRMED', {
        targetRef: lamp,
        command: 'identify',
        params: {},
        reason: 'DefaultResponse SUCCESS +90 ms, then no report, ever',
        resultOutcome: 'unconfirmed',
      }),
      makeAction('DISPATCHED', {
        targetRef: lamp,
        command: 'set_color_temp',
        params: { color_temp_kelvin: 4525 },
        reason: null,
        // bare dispatch: no settling record yet — provisional (§5.9); a late
        // command_result can settle this AFTER the run reads COMPLETED.
      }),
      makeAction('FAILED', {
        targetRef: lamp,
        command: 'turn_off',
        params: {},
        reason: 'device offline',
        resultOutcome: 'rejected',
      }),
    ],
  });
  const run = makeRun('run_fm_all', { ...A, triggeredAt: matched }); // ≡ matchedAt (DP-3)
  return {
    ...defaultDataset,
    automations: [makeAutomation('auto_fm', 'Evening lamp scene', { lastRunId: 'run_fm_all' })],
    runs: [run],
    causalChains: { run_fm_all: chain },
    nonFiring: { auto_fm: makeNonFiring('auto_fm', 'NEVER_TRIGGERED', { automationName: 'Evening lamp scene' }) },
  };
}

/* The live-fleet mirror (post-04P): one entity per deployed class — light ·
 * occupancy · switch · temp/hum/battery · contact · battery-only. Attribute keys
 * are SOURCE-DERIVED (canonical schema keys temperature_c / humidity_pct from the
 * W2 handlers; brightness 0–254 canonical + the DERIVED brightness_percent
 * decoration, MaterializedStateQueryService.java:113). A live probe of the Pi's
 * read-API was not reachable from this session — re-verify shapes at the first
 * live run (noted in the lane return).
 */
function buildLiveFleet(): MockDataset {
  const mk = (
    entityId: string,
    availability: EntitySummary['availability'],
    attrs: EntityState['attributes'],
    minAgo: number,
    stale = false,
  ): EntityState => ({
    entityId,
    availability,
    attributes: attrs,
    stateVersion: 3,
    lastChanged: iso(minAgo),
    lastUpdated: iso(minAgo),
    lastReported: iso(minAgo),
    stale,
    staleAfter: null,
  });
  const entityState: Record<string, EntityState> = {
    ent_hue_light: mk('ent_hue_light', 'AVAILABLE', {
      power: { t: 'BOOL', v: true },
      brightness: { t: 'NUMBER', v: 209 }, // canonical 0–254 level
      brightness_percent: { t: 'PERCENT', v: 82 }, // DERIVED at query time — the % the UI shows
    }, 3),
    ent_snzb03p_motion: mk('ent_snzb03p_motion', 'AVAILABLE', { occupancy: { t: 'BOOL', v: false }, battery: { t: 'PERCENT', v: 97 } }, 6),
    ent_s31_switch: mk('ent_s31_switch', 'AVAILABLE', { power: { t: 'BOOL', v: true } }, 1),
    ent_snzb02p_climate: mk('ent_snzb02p_climate', 'AVAILABLE', {
      temperature_c: { t: 'NUMBER', v: 23.41 },
      humidity_pct: { t: 'NUMBER', v: 47.2 },
      battery: { t: 'PERCENT', v: 100 },
    }, 9),
    ent_snzb04p_contact: mk('ent_snzb04p_contact', 'AVAILABLE', { contact: { t: 'BOOL', v: true }, battery: { t: 'PERCENT', v: 100 } }, 14),
    ent_snzb01p_button: mk('ent_snzb01p_button', 'AVAILABLE', { battery: { t: 'PERCENT', v: 100 } }, 45),
  };
  const entities: EntitySummary[] = Object.values(entityState).map((s) => ({
    entityId: s.entityId,
    availability: s.availability,
    stale: s.stale,
  }));
  return { ...defaultDataset, entities, entityState, entityDetail: {} };
}

/* THE LIVE PRESENT-BUT-NULL WIRE (FE-LIVE-V112 item 1 — the shape that actually
 * broke). Field evidence (WCAP-2 + the 2026-07-27 devtools-chain-glance return):
 * the live wire serves optionals as NULL BESIDE POPULATED SIBLINGS —
 * `resultOutcome: null` with `settled: true`; `reason`, `trigger.type`,
 * `automationName`, `firingValue` all observed null — where these mocks used to
 * emit populated-or-ABSENT only. The real seam is TRI-STATE (absent/null/value),
 * and the mocks were structurally blind to it: a fixture-green `.toLowerCase()`
 * crashed the chain render on live data and killed the polling loop. Three
 * exhibits, one per honest state:
 *   run_ln_nulls   — every nullable key PRESENT-BUT-NULL (the crash shape);
 *   run_ln_empty   — a real, successful, genuinely EMPTY chain (nothing failed);
 *   run_ln_missing — listed in runs[] with NO chain: the transport serves the
 *                    honest 404 problem (the retryable error-card case).
 */
function buildLiveNulls(): MockDataset {
  const A = { automationId: 'auto_ln_rotated' };
  // The crash shape: nulls beside populated siblings, exactly as captured.
  const nulls = makeChain('run_ln_nulls', {
    ...A,
    minAgo: 3,
    actions: [
      makeAction('CONFIRMED', {
        targetRef: { type: 'ENTITY', id: 'ent_livingroom_lamp' },
        reason: null,
        resultOutcome: null, // observed: null beside settled: true
        settled: true,
      }),
      makeAction('UNCONFIRMED', {
        targetRef: { type: 'ENTITY', id: 'ent_livingroom_lamp' },
        command: 'set_brightness',
        params: { brightness: 50 },
        reason: null, // observed: the recorded reason itself can be null
        resultOutcome: null,
        settled: true,
      }),
    ],
  });
  nulls.automationName = null; // identity rotation (lawful wire)
  nulls.trigger.type = null; // identity rotation (lawful wire)
  nulls.trigger.firingValue = null; // observed null in ALL eras — the .toLowerCase() crash field
  nulls.outcome.reason = null;

  // A real, successful, genuinely empty chain — no conditions, no actions,
  // nothing planned. Renders the honest empty note, never a blank or an error.
  const empty = makeChain('run_ln_empty', { ...A, automationName: 'Quiet automation', minAgo: 30 });
  empty.conditions = [];
  empty.actions = [];
  empty.outcome = { status: 'COMPLETED', reason: null, durationMs: 12, actionCount: 0, commandCount: 0 };

  const nullsRun = makeRun('run_ln_nulls', { ...A, minAgo: 3 });
  nullsRun.automationName = null;

  return {
    ...defaultDataset,
    automations: [makeAutomation('auto_ln_rotated', 'Quiet automation')],
    runs: [
      nullsRun,
      makeRun('run_ln_empty', { ...A, automationName: 'Quiet automation', minAgo: 30 }),
      // Listed but chainless: the mock transport 404s its causal-chain read —
      // the honest, retryable request-failed case (no chain fixture on purpose).
      makeRun('run_ln_missing', { ...A, automationName: 'Quiet automation', minAgo: 55 }),
    ],
    causalChains: { run_ln_nulls: nulls, run_ln_empty: empty },
    nonFiring: { auto_ln_rotated: makeNonFiring('auto_ln_rotated', 'NEVER_TRIGGERED', { automationName: 'Quiet automation' }) },
  };
}

// Connected but empty — exercises the "empty as teaching", never a blank panel.
function buildEmpty(): MockDataset {
  return {
    entities: [],
    entityDetail: {},
    entityState: {},
    // Wire-faithful A4/A5 (v1.1.1): an empty home still carries the ruled additive
    // extras — 0 entities, ready, and the platform subscribers all LIVE.
    projection: { mode: 'LIVE', viewPosition: base.projection.viewPosition, lagEvents: 0, projectionVersion: 5, entityCount: 0, ready: true },
    dlq: { depth: 0, parkedSubscribers: [], subscribers: base.dlq.subscribers },
    health: { phase: 'RUNNING', projection: { mode: 'LIVE', viewPosition: base.projection.viewPosition, lagEvents: 0 }, dlq: { depth: 0, parkedSubscribers: [] }, integrations: [] },
    automations: [],
    runs: [],
    causalChains: {},
    nonFiring: {},
    events: [],
  };
}

/* ---- FE-HONEST-1 (§10-J): the dangling-ref exhibit ---- */
/* The R-4 custody-clone class (F-R4-2): a rule whose `entity_ref`s belong to a
 * DIFFERENT hub's registry — the run record exists, but no entity in THIS
 * registry matches its refs. The old surface paraphrased over it ("it fires on
 * state change"); the law is a LOUD render: the named ULID, "not in this hub's
 * registry", visually failing. The trigger ULID below is the field exhibit,
 * verbatim (R-4 §10-J). */
function buildDanglingRef(): MockDataset {
  const GHOST_TRIGGER = '01KX1PB9AAB4VB3E10BD477TV3'; // the R-4 exhibit ULID
  const GHOST_TARGET = '01KX1PB9AAB4VB3E10BD477TVX';
  const chain = makeChain('run_dangling', {
    automationId: 'auto_dangling',
    automationName: 'Occupancy light (imported)',
    triggerId: GHOST_TRIGGER,
    targetId: GHOST_TARGET,
    outcome: 'UNCONFIRMED',
    minAgo: 45,
  });
  return {
    ...defaultDataset,
    automations: [
      ...defaultDataset.automations,
      makeAutomation('auto_dangling', 'Occupancy light (imported)', { lastRunId: 'run_dangling' }),
    ],
    runs: [
      makeRun('run_dangling', {
        automationId: 'auto_dangling',
        automationName: 'Occupancy light (imported)',
        minAgo: 45,
      }),
      ...defaultDataset.runs,
    ],
    causalChains: { ...defaultDataset.causalChains, run_dangling: chain },
    nonFiring: {
      ...defaultDataset.nonFiring,
      // The concealment exhibit AS THE WIRE SERVES IT TODAY: a triggerSummary in
      // friendly words with no ref to check (the non-firing read carries none —
      // the CONTRACT-GAP PROPOSAL in the FE-HONEST-1 return is what would let
      // this surface go loud too).
      auto_dangling: makeNonFiring('auto_dangling', 'NEVER_TRIGGERED', {
        automationName: 'Occupancy light (imported)',
        triggerSummary: 'This runs when a state changes.',
      }),
    },
  };
}

/* ---- HERO-1b B7 (2026-09-12): the hero-states scenario — SPEC §3 on today's wire ----
 * One run per §3 row today's emitter can produce, each in ONE era (audit O1: the mock never
 * shows a sentence the wire cannot back): COMPLETED × each outcome (rows 1–5), the silent
 * skip and the era skeleton (row 6's two arms), one each of SKIPPED / FAILED / CANCELLED /
 * INTERRUPTED (rows 11, 16, 19, 28-expired), and a replaced command (the mode override,
 * §10 sentence 6). The wire's null arms as they are: `firingValue` null everywhere (all
 * eras, 2026-07-27); `resultOutcome` null beside CONFIRMED (F-R4b-H — the zigbee handler
 * publishes command_result only on failure); a SKIPPED action has `command: null` (:776)
 * and keeps its planned target (:771 nulls it only when the plan names none). Anchored at
 * the most recent 9:42 pm (the §7 sample slot) so the §10 script reads off the screen. */
function buildHeroStates(): MockDataset {
  const A = { automationId: 'auto_hero', automationName: 'Evening Lights' };
  const light = { type: 'ENTITY', id: 'ent_hallway_light' };
  const anchor = new Date(now);
  anchor.setHours(21, 42, 0, 0);
  if (anchor.getTime() > now) anchor.setDate(anchor.getDate() - 1);
  const at = (minutesBefore: number) => new Date(anchor.getTime() - minutesBefore * 60_000).toISOString();
  const chain = (runId: string, minutesBefore: number, o: Omit<ChainOpts, 'matchedAtIso' | 'automationId' | 'automationName'>): CausalChain => {
    const c = makeChain(runId, { ...A, matchedAtIso: at(minutesBefore), ...o });
    c.trigger.firingValue = null; // today's wire: never a reading (EXPLAIN-1 waits)
    return c;
  };
  const confirmed = (over: Partial<CausalAction> = {}) => makeAction('CONFIRMED', { targetRef: light, resultOutcome: null, settled: true, ...over });
  const skipped = (over: Partial<CausalAction> = {}) => makeAction('SKIPPED', { targetRef: light, command: null, params: {}, resultOutcome: null, settled: true, ...over });
  const rows: [string, number, ChainOpts][] = [
    ['run_hs_01_confirmed', 0, { actions: [confirmed()] }],
    ['run_hs_02_dispatched', 5, { actions: [makeAction('DISPATCHED', { targetRef: light, resultOutcome: null, settled: false })], terminalReason: null }],
    ['run_hs_03_unconfirmed', 10, { actions: [makeAction('UNCONFIRMED', { targetRef: light, resultOutcome: null, settled: true })], terminalReason: 'Action sent; device did not confirm within 5s', durationMs: 5021 }],
    ['run_hs_04_failed', 15, { actions: [makeAction('FAILED', { targetRef: light, resultOutcome: 'rejected', reason: 'rejected' })] }],
    ['run_hs_05_skipped_step', 20, { actions: [skipped({ reason: 'Target unavailable' })] }],
    ['run_hs_06_replaced', 25, { actions: [makeAction('DISPATCHED', { targetRef: light, resultOutcome: 'superseded', settled: true })] }],
    ['run_hs_11_skipped_run', 40, { status: 'SKIPPED', conditionResult: false, actions: [skipped({ reason: 'Condition not met' })], terminalReason: 'Condition not met: before sunset', durationMs: 38 }],
    ['run_hs_16_failed_run', 55, { status: 'FAILED', actions: [makeAction('FAILED', { targetRef: light, resultOutcome: 'rejected', reason: 'rejected' })], terminalReason: 'Action failed: rejected', durationMs: 240 }],
    ['run_hs_19_cancelled_run', 70, { status: 'CANCELLED', actions: [confirmed()], terminalReason: 'Superseded by a newer run', durationMs: 900 }],
    ['run_hs_28_interrupted_run', 85, { status: 'INTERRUPTED', actions: [makeAction('FAILED', { targetRef: light, resultOutcome: 'expired_on_restart', reason: 'command was in-flight at restart and is not idempotent' })], terminalReason: 'System restarted mid-run', durationMs: 1200 }],
  ];
  const causalChains: Record<string, CausalChain> = {};
  const runs: RunSummary[] = [];
  for (const [id, min, o] of rows) {
    const c = chain(id, min, o);
    causalChains[id] = c;
    runs.push(makeRun(id, { ...A, triggeredAt: c.trigger.matchedAt, status: c.outcome.status, terminalReason: c.outcome.reason }));
  }
  // Row 6a — the silent skip: planned steps, nothing sent, empty actions[] (§3.9 per-target skips).
  const silent = chain('run_hs_06a_silent_skip', 30, { actions: [] });
  silent.outcome = { status: 'COMPLETED', reason: null, durationMs: 41, actionCount: 2, commandCount: 0 };
  causalChains[silent.runId] = silent;
  runs.push(makeRun(silent.runId, { ...A, triggeredAt: silent.trigger.matchedAt }));
  // Row 6b — the era skeleton: a run from before the current automations were loaded
  // (the prior-instance class): name null, trigger type null, its triggering event
  // outside the run's correlation, no steps on record. Permanent for this run.
  const era = chain('run_hs_06b_era_skeleton', 35, { actions: [] });
  era.automationName = null;
  era.trigger.type = null;
  era.trigger.subjectRef = null;
  era.conditions = [];
  era.outcome = { status: 'COMPLETED', reason: null, durationMs: 12, actionCount: 0, commandCount: 0 };
  causalChains[era.runId] = era;
  const eraRun = makeRun(era.runId, { ...A, triggeredAt: era.trigger.matchedAt });
  eraRun.automationName = null;
  runs.push(eraRun);
  return {
    ...defaultDataset,
    automations: [
      makeAutomation('auto_hero', 'Evening Lights', { lastRunId: 'run_hs_01_confirmed' }),
      makeAutomation('auto_hero_porch', 'Porch Light', { lastRunId: null }),
      makeAutomation('auto_hero_welcome', 'Front Door Welcome', { lastRunId: 'run_hs_11_skipped_run' }),
    ],
    runs,
    causalChains,
    nonFiring: {
      // The why-not rows the §10 script reads: (3) never triggered, no run · (4) a condition was false.
      // DP-B2 as Core writes it (StandardExplanationService:355–:358): NEVER_TRIGGERED with a run id.
      auto_hero: makeNonFiring('auto_hero', 'NEVER_TRIGGERED', { automationName: 'Evening Lights', lastRelevantRunId: 'run_hs_01_confirmed', explanation: `Automation 'Evening Lights' last fired and confirmed at ${at(0)}; no non-firing was detected in the requested window.`, triggerSummary: 'motion in the hallway', lastEvaluation: { at: at(0), conditionsResult: 'true' } }),
      auto_hero_porch: makeNonFiring('auto_hero_porch', 'NEVER_TRIGGERED', { automationName: 'Porch Light', triggerSummary: 'motion on the porch', triggerRef: null }),
      auto_hero_welcome: makeNonFiring('auto_hero_welcome', 'CONDITION_NOT_MET', { automationName: 'Front Door Welcome', lastRelevantRunId: 'run_hs_11_skipped_run', triggerSummary: 'the front door opening', lastEvaluation: { at: at(40), conditionsResult: 'false' } }),
    },
  };
}

/* ---- The registry ---- */
/* FE-115 D2 — `legacy-hub`: the default home as a pre-v1.1.4 hub serves it. The ONE scenario that keeps the
 * ABSENT arm of every v1.1.4 / v1.1.5 key reachable (the tri-state's third state; the two recorded 2026-08
 * fixtures are this era on the non-firing read). The keys are STRIPPED (never nulled) from a deep copy of the
 * default dataset; the v1.1.2 / v1.1.3 keys stay — a v1.1.3 hub, not a v1.1 one. */
function buildLegacyHub(): MockDataset {
  const d = structuredClone(defaultDataset);
  for (const c of Object.values(d.causalChains)) {
    delete c.definitionKey;
    for (const cond of c.conditions) delete cond.definition;
    for (const a of c.actions) {
      delete a.settledAt;
      delete a.confirmedAt;
    }
  }
  for (const n of Object.values(d.nonFiring)) {
    delete n.disabledAt;
    delete n.disabledReason;
    delete n.definitionKey;
  }
  for (const a of d.automations) delete a.definitionKey;
  return d;
}

/* FE-115 D2 — `v115-keys`: one DevPanel scenario per key STATE, so every sentence FE-114 (EXPLAIN-6 · 8 · 9) and
 * FE-115 (EXPLAIN-4) render is reachable by hand: one run per condition-definition permit the emitter can produce
 * (ConditionDefinitionRenderer: state · numeric · time · and · or · not · zone), a run whose definition is null
 * (the projection could not vouch — its definitionKey null too), a run whose definition `type` this build does
 * not know (the open vocabulary), a confirmed step WITH its confirmedAt and a held DISPATCHED step without
 * (settledAt / confirmedAt both null), a DISABLED automation with its disabledAt / disabledReason, and a
 * FIRED_CONFIRMED verdict with its run id. */
function buildV115Keys(): MockDataset {
  const A = { automationId: 'auto_v115', automationName: 'Evening scene rules' };
  const motion = { type: 'ENTITY', id: 'ent_hallway_motion' };
  const lamp = { type: 'ENTITY', id: 'ent_livingroom_lamp' };
  const state = def('StateCondition', { selector: 'ent_hallway_motion', attribute: 'occupancy', value: 'detected' });
  const numeric = def('NumericCondition', { selector: 'ent_livingroom_lamp', attribute: 'brightness', above: 10, below: 200 });
  const time = def('TimeCondition', { after: '18:00', before: '23:30' });
  const rows: { id: string; min: number; definition: ConditionDefinition | null; expression: string; result?: boolean; definitionKey?: null; actions?: CausalAction[] }[] = [
    { id: 'run_v115_state', min: 2, definition: state, expression: 'StateCondition' },
    { id: 'run_v115_numeric', min: 7, definition: numeric, expression: 'NumericCondition' },
    { id: 'run_v115_time', min: 12, definition: time, expression: 'TimeCondition' },
    { id: 'run_v115_and', min: 18, definition: def('AndCondition', {}, [state, time]), expression: 'AndCondition' },
    { id: 'run_v115_or', min: 25, definition: def('OrCondition', {}, [numeric, def('TimeCondition', { after: '06:30' })]), expression: 'OrCondition' },
    { id: 'run_v115_not', min: 33, definition: def('NotCondition', {}, [state]), expression: 'NotCondition', result: false },
    { id: 'run_v115_zone', min: 41, definition: def('ZoneCondition'), expression: 'ZoneCondition' },
    { id: 'run_v115_nested', min: 48, definition: def('AndCondition', {}, [def('OrCondition', {}, [state, numeric]), def('NotCondition', {}, [time])]), expression: 'AndCondition' },
    { id: 'run_v115_null', min: 95, definition: null, expression: 'StateCondition', definitionKey: null },
    { id: 'run_v115_unknown', min: 130, definition: def('PresenceCondition', { selector: 'area:hallway/PRIMARY' }), expression: 'PresenceCondition' },
    {
      id: 'run_v115_held',
      min: 1,
      definition: AFTER_SUNSET_DEF(),
      expression: 'NumericCondition',
      actions: [makeAction('DISPATCHED', { targetRef: lamp, settled: false, reason: null })],
    },
  ];
  const runs: RunSummary[] = [];
  const causalChains: Record<string, CausalChain> = {};
  for (const r of rows) {
    const status: RunStatus = r.result === false ? 'SKIPPED' : 'COMPLETED';
    runs.push(makeRun(r.id, { ...A, status, minAgo: r.min }));
    const c = makeChain(r.id, {
      ...A,
      status,
      minAgo: r.min,
      triggerId: motion.id,
      targetId: lamp.id,
      ...(r.definitionKey === null ? { definitionKey: null } : {}),
      ...(r.actions ? { actions: r.actions } : {}),
    });
    c.conditions = [makeCondition(r.result ?? true, { expression: r.expression, definition: r.definition })];
    causalChains[r.id] = c;
  }
  return {
    ...defaultDataset,
    automations: [
      makeAutomation('auto_v115', 'Evening scene rules', { lastRunId: 'run_v115_state' }),
      makeAutomation('auto_v115_disabled', 'Porch light (turned off)', { enabled: false, lastRunId: null }),
      makeAutomation('auto_v115_fired', 'Bedtime lamp', { lastRunId: 'run_v115_state' }),
    ],
    runs,
    causalChains,
    nonFiring: {
      auto_v115: makeNonFiring('auto_v115', 'CONDITION_NOT_MET', { automationName: 'Evening scene rules', lastRelevantRunId: 'run_v115_not' }),
      auto_v115_disabled: makeNonFiring('auto_v115_disabled', 'DISABLED', { automationName: 'Porch light (turned off)' }),
      auto_v115_fired: makeNonFiring('auto_v115_fired', 'FIRED_CONFIRMED', { automationName: 'Bedtime lamp', lastRelevantRunId: 'run_v115_state' }),
    },
  };
}

export interface Scenario {
  id: string;
  label: string;
  group: 'Story' | 'Scale';
  blurb: string;
  build: () => MockDataset;
}

export const SCENARIOS: Scenario[] = [
  { id: 'default', label: 'Coherent home', group: 'Story', blurb: 'The baseline: motion→light confirmed, one honest unconfirmed, mixed origins.', build: () => defaultDataset },
  { id: 'all-outcomes', label: 'All outcomes', group: 'Story', blurb: 'One automation, every command outcome + run status — confirmed, sent-not-confirmed, failed, skipped, cancelled, interrupted.', build: buildAllOutcomes },
  { id: 'cascade', label: 'Cascade', group: 'Story', blurb: 'A run that triggered another — the child links back to “what triggered this”.', build: buildCascade },
  { id: 'all-verdicts', label: 'All “why not?” verdicts', group: 'Story', blurb: 'Condition-not-met, never-triggered, acted-but-unconfirmed, disabled.', build: buildAllVerdicts },
  { id: 'e5-confirmation', label: 'Confirmation, measured', group: 'Story', blurb: 'AMD-97 honest states at measured timing: color confirms slowly (flips live ~8s in), idempotent confirmed-from-cache, effect honestly unconfirmed, superseded expiry.', build: buildE5Confirmation },
  { id: 'five-modes', label: 'The five failure modes', group: 'Story', blurb: 'The ruled v1.1.2 wire: timed-out, replaced, accepted-never-confirmed, still-settling, and failed — pairwise distinct, never collapsed. One is provisional (§5.9).', build: buildFiveModes },
  { id: 'verdict-vocabulary', label: 'The ten verdicts (pre-v1.1.2 wire)', group: 'Story', blurb: 'Every command_result outcome as the pre-SKIP-VIS deployed wire flattens it — the recorded-reason recovery path, kept for pre-v1.1.2 payloads until the deploy.', build: buildVerdictVocabulary },
  { id: 'field-evidence', label: 'Field evidence', group: 'Story', blurb: 'The silent-skip do-nothing run, the null-name prior-instance run, rehydrated “Available” with days-old evidence, and honest UNKNOWN since restart.', build: buildFieldEvidence },
  { id: 'live-nulls', label: 'Live wire: present-but-null', group: 'Story', blurb: 'The tri-state seam as the live wire serves it — every nullable key present-but-null, a genuinely empty chain, and a run whose chain read 404s.', build: buildLiveNulls },
  { id: 'hero-states', label: 'The hero, every state', group: 'Story', blurb: 'SPEC §3 on today’s wire: one run per headline row the emitter can produce — each outcome, the silent skip, the era skeleton, a skipped / failed / cancelled / interrupted run, a replaced command — with the wire’s nulls as they are (no firing value; no verdict row beside Confirmed).', build: buildHeroStates },
  { id: 'dangling-ref', label: 'Dangling ref (loud)', group: 'Story', blurb: 'The R-4 custody-clone class: a run whose entity refs are not in this hub’s registry — rendered loud on the chain, never paraphrased away.', build: buildDanglingRef },
  { id: 'v115-keys', label: 'v1.1.4 / v1.1.5 keys', group: 'Story', blurb: 'One run per condition-definition kind (state · numeric · time · and · or · not · zone, a nested one), a null definition and an unknown kind; a confirmed step with its confirmedAt and a held one without; a DISABLED with its disabledAt and a FIRED_CONFIRMED — every FE-114 / FE-115 sentence one click away.', build: buildV115Keys },
  { id: 'legacy-hub', label: 'Legacy hub (pre-v1.1.4)', group: 'Story', blurb: 'The default home as a v1.1.3 hub serves it — no definitionKey, no condition definition, no settledAt / confirmedAt, no disabledAt: the ABSENT arm of every v1.1.4 / v1.1.5 key stays reachable.', build: buildLegacyHub },
  { id: 'live-fleet', label: 'Live fleet mirror', group: 'Story', blurb: 'One entity per deployed device class with canonical attribute keys — including brightness level 0–254 plus the hub-derived percent.', build: buildLiveFleet },
  { id: 'all-origins', label: 'All event origins', group: 'Story', blurb: 'Automation, device, you, external, and the honest UNKNOWN.', build: buildAllOrigins },
  { id: 'large', label: 'Large (300 runs · 500 events)', group: 'Scale', blurb: 'Forces list virtualization + a render budget.', build: buildLarge },
  { id: 'empty', label: 'Empty (fresh install)', group: 'Scale', blurb: 'Connected but nothing has happened yet — empty states that teach.', build: buildEmpty },
];

export const DEFAULT_SCENARIO_ID = 'default';

export function resolveScenario(id: string): MockDataset {
  const s = SCENARIOS.find((x) => x.id === id);
  return (s ?? SCENARIOS[0]!).build();
}
