/*
 * HomeSynapse — Mock SCENARIOS (T1.2, the pre-hardware sprint keystone).
 * ---------------------------------------------------------------------------
 * A scenario system that can produce EVERY condition the FROZEN v1.1 contract allows, on
 * demand — so the mock demo is complete now, FE-4 can verify every state on realistic data,
 * and live-integration (FE-1) meets no shape it hasn't already faced. Every dataset is shaped
 * by the same contract types the real transport returns; contract.test.ts validates them.
 *
 * Two orthogonal dimensions (see mockState.ts): a DATA scenario (the story the data tells) and
 * a TRANSPORT condition (replaying / offline / slow / 401 / 403 / etag). This file owns the data.
 *
 * Bundle note: variant datasets are built lazily (`build()`), and large lists are GENERATED by
 * code (not materialized literals), so the static footprint stays small — mock ships in the
 * demo/website-embed builds (sprint §T1.2), and we keep the 100 KB budget honest.
 */
import type {
  AutomationSummary,
  CausalAction,
  CausalChain,
  CausalCondition,
  ConsolidatedHealth,
  DlqStatus,
  EntityDetail,
  EntityState,
  EntitySummary,
  EventSummary,
  NonFiringExplanation,
  Origin,
  ProjectionStatus,
  RunStatus,
  ActionOutcome,
  NonFiringVerdict,
  RunSummary,
} from '../contract';
import * as base from './mockData';

/** The full fixture bundle a scenario serves. Mirrors the endpoints in mockTransport. */
export interface MockDataset {
  entities: EntitySummary[];
  entityDetail: Record<string, EntityDetail>;
  entityState: Record<string, EntityState>;
  projection: ProjectionStatus;
  dlq: DlqStatus;
  health: ConsolidatedHealth;
  automations: AutomationSummary[];
  runs: RunSummary[];
  causalChains: Record<string, CausalChain>;
  nonFiring: Record<string, NonFiringExplanation>;
  events: EventSummary[];
}

const now = Date.now();
const iso = (minAgo: number) => new Date(now - minAgo * 60_000).toISOString();
let evSeq = 90_000;
const nextEvVp = () => ++evSeq;

/* ---- Contract-shaped factories (defaults + overrides; keep every field on-contract) ---- */

const ACTION_REASON: Record<ActionOutcome, string | null> = {
  CONFIRMED: null,
  DISPATCHED: null,
  UNCONFIRMED: 'No state_confirmed within the 5s timeout',
  FAILED: 'Device unreachable — the command was rejected',
  SKIPPED: 'A condition was not met',
};

function makeAction(outcome: ActionOutcome, over: Partial<CausalAction> = {}): CausalAction {
  return {
    type: 'device_command',
    targetRef: { type: 'ENTITY', id: 'ent_hallway_light' },
    command: 'turn_on',
    params: outcome === 'SKIPPED' ? {} : { brightness: 82 },
    outcome,
    reason: ACTION_REASON[outcome],
    ...over,
  };
}

function makeCondition(result: boolean, over: Partial<CausalCondition> = {}): CausalCondition {
  return {
    expression: 'time is after sunset',
    evaluated: true,
    result,
    observedState: [{ entityId: 'sys_sun', attribute: 'elevation', value: result ? '-6.2°' : '+24.7°' }],
    ...over,
  };
}

interface ChainOpts {
  automationId?: string;
  automationName?: string;
  outcome?: ActionOutcome;
  status?: RunStatus;
  conditionResult?: boolean;
  parentRunId?: string | null;
  depth?: number;
  triggerId?: string;
  targetId?: string;
  terminalReason?: string | null;
  durationMs?: number;
  minAgo?: number;
  /** Exact trigger time (overrides minAgo) — for scenarios anchored to build time. */
  matchedAtIso?: string;
  /** Full actions override (e.g. the E5 multi-action / live-flip chains). */
  actions?: CausalAction[];
}

function makeChain(runId: string, o: ChainOpts = {}): CausalChain {
  const status = o.status ?? 'COMPLETED';
  const outcome = o.outcome ?? (status === 'SKIPPED' ? 'SKIPPED' : 'CONFIRMED');
  const condResult = o.conditionResult ?? status !== 'SKIPPED';
  const actions =
    o.actions ?? [makeAction(outcome, { targetRef: { type: 'ENTITY', id: o.targetId ?? 'ent_hallway_light' } })];
  return {
    runId,
    automationId: o.automationId ?? 'auto_demo',
    automationName: o.automationName ?? 'Demo automation',
    trigger: {
      type: 'state_changed',
      subjectRef: { type: 'ENTITY', id: o.triggerId ?? 'ent_hallway_motion' },
      matchedAt: o.matchedAtIso ?? iso(o.minAgo ?? 2),
      firingValue: 'motion = detected',
    },
    conditions: [makeCondition(condResult)],
    actions,
    outcome: {
      status,
      reason: o.terminalReason ?? null,
      durationMs: o.durationMs ?? 412,
      actionCount: actions.length,
      commandCount: actions.filter((a) => a.outcome !== 'SKIPPED').length,
    },
    cascade: { parentRunId: o.parentRunId ?? null, depth: o.depth ?? 0 },
  };
}

function makeRun(runId: string, o: Partial<RunSummary> & { minAgo?: number } = {}): RunSummary {
  return {
    runId,
    automationId: o.automationId ?? 'auto_demo',
    automationName: o.automationName ?? 'Demo automation',
    triggeredAt: o.triggeredAt ?? iso(o.minAgo ?? 2),
    status: o.status ?? 'COMPLETED',
    terminalReason: o.terminalReason ?? null,
  };
}

function makeEvent(eventId: string, origin: Origin, over: Partial<EventSummary> = {}): EventSummary {
  const SUMMARY: Record<Origin, string> = {
    AUTOMATION: 'Hallway Light turned on',
    DEVICE: 'Hallway Motion detected motion',
    USER: 'Living Room Lamp turned off from the app',
    EXTERNAL: 'Kitchen Light changed outside the system',
    UNKNOWN: 'Kitchen Light reported a brightness change',
  };
  return {
    eventId,
    type: 'state_changed',
    category: 'STATE',
    occurredAt: iso(1),
    viewPosition: nextEvVp(),
    subjectRef: { type: 'ENTITY', id: 'ent_hallway_light' },
    correlationId: 'cor_demo',
    causationId: null,
    origin,
    summary: SUMMARY[origin],
    ...over,
  };
}

function makeNonFiring(
  automationId: string,
  verdict: NonFiringVerdict,
  over: Partial<NonFiringExplanation> = {},
): NonFiringExplanation {
  const EXPLAIN: Record<NonFiringVerdict, string> = {
    CONDITION_NOT_MET: 'It did not run because it was before sunset when the trigger fired.',
    NEVER_TRIGGERED: 'Nothing set it off. The trigger has not matched in the last hour.',
    ACTED_BUT_UNCONFIRMED: 'It ran, but the device never confirmed it acted — it may be slow or briefly offline.',
    DISABLED: 'This automation is turned off, so it cannot run.',
  };
  return {
    automationId,
    automationName: over.automationName ?? 'Demo automation',
    enabled: verdict !== 'DISABLED',
    verdict,
    lastRelevantRunId: verdict === 'CONDITION_NOT_MET' || verdict === 'ACTED_BUT_UNCONFIRMED' ? 'run_demo_ref' : null,
    explanation: EXPLAIN[verdict],
    triggerSummary: 'This runs when Hallway Motion detects motion, after sunset.',
    lastEvaluation:
      verdict === 'CONDITION_NOT_MET'
        ? { at: iso(30), conditionsResult: 'after sunset = false' }
        : { at: null, conditionsResult: null },
    ...over,
  };
}

function makeAutomation(automationId: string, name: string, over: Partial<AutomationSummary> = {}): AutomationSummary {
  return {
    automationId,
    name,
    enabled: true,
    components: [
      { type: 'trigger', summary: 'When Hallway Motion detects motion' },
      { type: 'condition', summary: 'Only after sunset' },
      { type: 'action', summary: 'Turn on Hallway Light' },
    ],
    lastRunId: null,
    ...over,
  };
}

/* ---- The default coherent home (the current fixtures) ---- */
export const defaultDataset: MockDataset = {
  entities: base.entities,
  entityDetail: base.entityDetail,
  entityState: base.entityState,
  projection: base.projection,
  dlq: base.dlq,
  health: base.health,
  automations: base.automations,
  runs: base.runs,
  causalChains: base.causalChains,
  nonFiring: base.nonFiring,
  events: base.events,
};

/* ---- Variant builders ---- */

// Every command outcome + every run status, one automation, as a run list you can click through.
function buildAllOutcomes(): MockDataset {
  const A = { automationId: 'auto_demo', automationName: 'Demo automation' };
  const specs: { id: string; outcome: ActionOutcome; status: RunStatus; reason?: string | null; min: number }[] = [
    { id: 'run_oc_confirmed', outcome: 'CONFIRMED', status: 'COMPLETED', min: 2 },
    { id: 'run_oc_dispatched', outcome: 'DISPATCHED', status: 'COMPLETED', reason: 'Command sent; awaiting confirmation', min: 4 },
    { id: 'run_oc_unconfirmed', outcome: 'UNCONFIRMED', status: 'COMPLETED', reason: 'Action sent; device did not confirm within 5s', min: 9 },
    { id: 'run_oc_failed', outcome: 'FAILED', status: 'FAILED', reason: 'Device unreachable', min: 22 },
    { id: 'run_oc_skipped', outcome: 'SKIPPED', status: 'SKIPPED', reason: 'Condition not met: before sunset', min: 40 },
    { id: 'run_oc_cancelled', outcome: 'SKIPPED', status: 'CANCELLED', reason: 'Superseded by a newer run', min: 70 },
    { id: 'run_oc_interrupted', outcome: 'FAILED', status: 'INTERRUPTED', reason: 'System restarted mid-run', min: 130 },
  ];
  const runs = specs.map((s) => makeRun(s.id, { ...A, status: s.status, terminalReason: s.reason ?? null, minAgo: s.min }));
  const causalChains: Record<string, CausalChain> = {};
  for (const s of specs) {
    causalChains[s.id] = makeChain(s.id, {
      ...A,
      outcome: s.outcome,
      status: s.status,
      conditionResult: s.status !== 'SKIPPED',
      terminalReason: s.reason ?? null,
      minAgo: s.min,
    });
  }
  return {
    ...defaultDataset,
    automations: [makeAutomation('auto_demo', 'Demo automation', { lastRunId: 'run_oc_confirmed' })],
    runs,
    causalChains,
    nonFiring: { auto_demo: makeNonFiring('auto_demo', 'NEVER_TRIGGERED', { automationName: 'Demo automation' }) },
  };
}

// A parent → child cascade: one run triggers another; the child links back to its cause.
function buildCascade(): MockDataset {
  const parent = makeChain('run_casc_parent', {
    automationId: 'auto_sunset',
    automationName: 'Sunset Scene',
    triggerId: 'sys_sun',
    targetId: 'ent_livingroom_lamp',
    minAgo: 3,
  });
  parent.trigger = { type: 'time', subjectRef: { type: 'SYSTEM', id: 'sys_sun' }, matchedAt: iso(3), firingValue: 'sun set' };
  const child = makeChain('run_casc_child', {
    automationId: 'auto_evening_hallway',
    automationName: 'Evening Hallway Light',
    parentRunId: 'run_casc_parent',
    depth: 1,
    minAgo: 3,
  });
  return {
    ...defaultDataset,
    automations: [
      makeAutomation('auto_sunset', 'Sunset Scene', { lastRunId: 'run_casc_parent' }),
      makeAutomation('auto_evening_hallway', 'Evening Hallway Light', { lastRunId: 'run_casc_child' }),
    ],
    runs: [
      makeRun('run_casc_child', { automationId: 'auto_evening_hallway', automationName: 'Evening Hallway Light', minAgo: 3 }),
      makeRun('run_casc_parent', { automationId: 'auto_sunset', automationName: 'Sunset Scene', minAgo: 3 }),
    ],
    causalChains: { run_casc_parent: parent, run_casc_child: child },
  };
}

// All four "why didn't it fire?" verdicts, one automation each.
function buildAllVerdicts(): MockDataset {
  const defs: { id: string; name: string; verdict: NonFiringVerdict }[] = [
    { id: 'auto_v_condition', name: 'Front Door Welcome', verdict: 'CONDITION_NOT_MET' },
    { id: 'auto_v_never', name: 'Evening Hallway Light', verdict: 'NEVER_TRIGGERED' },
    { id: 'auto_v_acted', name: 'Bedtime Lights Off', verdict: 'ACTED_BUT_UNCONFIRMED' },
    { id: 'auto_v_disabled', name: 'Bedroom Night Light', verdict: 'DISABLED' },
  ];
  const nonFiring: Record<string, NonFiringExplanation> = {};
  for (const d of defs) nonFiring[d.id] = makeNonFiring(d.id, d.verdict, { automationName: d.name });
  return {
    ...defaultDataset,
    automations: defs.map((d) => makeAutomation(d.id, d.name, { enabled: d.verdict !== 'DISABLED' })),
    nonFiring,
  };
}

// Every event origin, including the honest UNKNOWN (never a silent blank).
function buildAllOrigins(): MockDataset {
  const origins: Origin[] = ['AUTOMATION', 'DEVICE', 'USER', 'EXTERNAL', 'UNKNOWN'];
  return {
    ...defaultDataset,
    events: origins.map((o, i) => makeEvent(`evt_origin_${i}`, o, { occurredAt: iso(i + 1) })),
  };
}

// Hundreds of rows — the input that forces list virtualization (T2.3) and stresses render-at-scale.
function buildLarge(): MockDataset {
  const STATUSES: RunStatus[] = ['COMPLETED', 'FAILED', 'SKIPPED', 'CANCELLED', 'INTERRUPTED'];
  const OUTCOMES: ActionOutcome[] = ['CONFIRMED', 'DISPATCHED', 'UNCONFIRMED', 'FAILED', 'SKIPPED'];
  const ORIGINS: Origin[] = ['AUTOMATION', 'DEVICE', 'USER', 'EXTERNAL', 'UNKNOWN'];
  const runs: RunSummary[] = [];
  const causalChains: Record<string, CausalChain> = {};
  for (let i = 0; i < 300; i++) {
    const id = `run_lg_${String(i).padStart(4, '0')}`;
    const status = STATUSES[i % STATUSES.length]!;
    const outcome = OUTCOMES[i % OUTCOMES.length]!;
    runs.push(makeRun(id, { status, minAgo: i * 7 + 2, terminalReason: status === 'COMPLETED' ? null : `${status.toLowerCase()} (#${i})` }));
    causalChains[id] = makeChain(id, { outcome, status, minAgo: i * 7 + 2 });
  }
  const events: EventSummary[] = [];
  for (let i = 0; i < 500; i++) {
    events.push(makeEvent(`evt_lg_${String(i).padStart(4, '0')}`, ORIGINS[i % ORIGINS.length]!, { occurredAt: iso(i + 1) }));
  }
  return { ...defaultDataset, automations: [makeAutomation('auto_demo', 'Demo automation')], runs, causalChains, events };
}

/* The four MEASURED confirmation-rendering semantics (AMD-97, ratified 2026-07-01; measured
 * truth: nexsys-bench/corpus/devices/philips-hue-white-a19.md). Each behavior is one click:
 *  1. run_e5_ct         — color confirms SLOWLY and legitimately: DISPATCHED flips to CONFIRMED
 *                         ~8.4s after scenario activation (the measured upper command→report
 *                         sample), rendered live by the poll. Calm pending inside the window.
 *  2. run_e5_idempotent — no-change ⇒ no report: the backend confirms from cache/readback and
 *                         SAYS so; the UI renders the honest terminal state, never a spinner.
 *  3. run_e5_effect     — identify/effect class: acknowledged but never reported ⇒ honest
 *                         UNCONFIRMED immediately (an ACK is not confirmation).
 *  4. run_e5_superseded — rapid re-command coalesces reporting: the older expectation EXPIRES
 *                         (honest unconfirmed, never false-fail/false-confirm); no stale chip.
 * The timing values live in the corpus + Doc 08 §3.6 — the UI itself runs NO timeout; only
 * this mock (standing in for Core's confirmation engine) knows the window.
 */
function buildE5Confirmation(): MockDataset {
  const t0 = Date.now(); // scenario-activation anchor (NOT the module-load `now`)
  const at = (msAgo: number) => new Date(t0 - msAgo).toISOString();
  const CT_CONFIRM_MS = 8_400; // measured upper bound: 447-mired command→report 20:23:40.575→:48.999

  const lamp = { type: 'ENTITY', id: 'ent_livingroom_lamp' };
  const confirmed = () => Date.now() - t0 >= CT_CONFIRM_MS;

  // 1 — the live-flipping CT action (getters re-evaluate on every poll read).
  const ctAction: CausalAction = {
    type: 'device_command',
    targetRef: lamp,
    command: 'set_color_temperature',
    params: { color_temp_kelvin: 2700 },
    get outcome(): ActionOutcome {
      return confirmed() ? 'CONFIRMED' : 'DISPATCHED';
    },
    get reason(): string | null {
      return confirmed() ? 'The device reported the new color temperature.' : null;
    },
  };

  const chains: Record<string, CausalChain> = {
    run_e5_ct: makeChain('run_e5_ct', {
      automationId: 'auto_e5',
      automationName: 'Evening Color Scene',
      matchedAtIso: at(1_000),
      actions: [ctAction],
      durationMs: 240,
    }),
    run_e5_idempotent: makeChain('run_e5_idempotent', {
      automationId: 'auto_e5',
      automationName: 'Evening Color Scene',
      matchedAtIso: at(40_000),
      actions: [
        makeAction('CONFIRMED', {
          targetRef: lamp,
          command: 'turn_on',
          params: {},
          reason: 'Already on — confirmed from the device’s current state (no change to report).',
        }),
      ],
      durationMs: 180,
    }),
    run_e5_effect: makeChain('run_e5_effect', {
      automationId: 'auto_e5',
      automationName: 'Evening Color Scene',
      matchedAtIso: at(90_000),
      actions: [
        makeAction('UNCONFIRMED', {
          targetRef: lamp,
          command: 'identify',
          params: {},
          reason: 'The device acknowledged this command but never reports performing it.',
        }),
      ],
      durationMs: 150,
    }),
    run_e5_superseded: makeChain('run_e5_superseded', {
      automationId: 'auto_e5',
      automationName: 'Evening Color Scene',
      matchedAtIso: at(150_000),
      actions: [
        makeAction('UNCONFIRMED', {
          targetRef: lamp,
          command: 'set_color_temperature',
          params: { color_temp_kelvin: 3500 },
          reason: 'Superseded — a newer color command replaced this one before the device reported.',
        }),
        makeAction('CONFIRMED', {
          targetRef: lamp,
          command: 'set_color_temperature',
          params: { color_temp_kelvin: 2200 },
          reason: null,
        }),
      ],
      durationMs: 620,
    }),
  };

  const runSpecs: { id: string; msAgo: number }[] = [
    { id: 'run_e5_ct', msAgo: 1_000 },
    { id: 'run_e5_idempotent', msAgo: 40_000 },
    { id: 'run_e5_effect', msAgo: 90_000 },
    { id: 'run_e5_superseded', msAgo: 150_000 },
  ];

  return {
    ...defaultDataset,
    automations: [makeAutomation('auto_e5', 'Evening Color Scene', { lastRunId: 'run_e5_ct' })],
    runs: runSpecs.map((r) =>
      makeRun(r.id, {
        automationId: 'auto_e5',
        automationName: 'Evening Color Scene',
        triggeredAt: at(r.msAgo),
        status: 'COMPLETED',
      }),
    ),
    causalChains: chains,
    nonFiring: { auto_e5: makeNonFiring('auto_e5', 'NEVER_TRIGGERED', { automationName: 'Evening Color Scene' }) },
  };
}

/* The TEN-value command_result vocabulary (CommandResultEvent.java:22-27), as it
 * actually reaches the frozen v1.1 causal-chain read TODAY: Core's explanation
 * service flattens every non-acknowledged result into outcome:FAILED
 * (StandardExplanationService.isFailure), with the truth surviving only in the
 * RECORDED REASON. This scenario reproduces that wire faithfully — the two
 * deterministic ledger disposition strings verbatim (StandardPendingCommandLedger
 * .java:912-916 / :922-924), bare outcome tokens for the rest — so the UI's
 * honest-verdict recovery (lib/verdicts.ts) is exercised against wire truth, and
 * the flattening's cost is demonstrable to a stranger in one click.
 */
function buildVerdictVocabulary(): MockDataset {
  const A = { automationId: 'auto_vv', automationName: 'Verdict vocabulary' };
  // [outcome-on-the-wire, recorded reason (wire-faithful), minutes ago]
  const flattened: { id: string; reason: string; min: number }[] = [
    {
      id: 'run_vv_superseded',
      reason:
        'superseded by a newer command on the same attribute; superseding command event 01JVVDEMO0000000000000000',
      min: 4,
    },
    { id: 'run_vv_expired', reason: 'command was in-flight at restart and is not idempotent', min: 8 },
    { id: 'run_vv_rejected', reason: 'rejected', min: 12 },
    { id: 'run_vv_timed_out', reason: 'timed_out', min: 16 },
    { id: 'run_vv_invalid', reason: 'invalid', min: 20 },
    { id: 'run_vv_unsupported', reason: 'unsupported', min: 24 },
    { id: 'run_vv_handler_error', reason: 'handler_error', min: 28 },
    { id: 'run_vv_integration', reason: 'integration_unavailable', min: 32 },
    { id: 'run_vv_unconfirmed', reason: 'unconfirmed', min: 36 },
  ];
  const runs: RunSummary[] = [];
  const causalChains: Record<string, CausalChain> = {};
  // The confirmed baseline (acknowledged → state_confirmed → CONFIRMED).
  runs.push(makeRun('run_vv_confirmed', { ...A, minAgo: 2 }));
  causalChains['run_vv_confirmed'] = makeChain('run_vv_confirmed', { ...A, outcome: 'CONFIRMED', minAgo: 2 });
  for (const f of flattened) {
    runs.push(makeRun(f.id, { ...A, status: 'COMPLETED', minAgo: f.min }));
    causalChains[f.id] = makeChain(f.id, {
      ...A,
      status: 'COMPLETED',
      minAgo: f.min,
      actions: [makeAction('FAILED', { reason: f.reason })],
    });
  }
  return {
    ...defaultDataset,
    automations: [makeAutomation('auto_vv', 'Verdict vocabulary', { lastRunId: 'run_vv_confirmed' })],
    runs,
    causalChains,
    nonFiring: { auto_vv: makeNonFiring('auto_vv', 'NEVER_TRIGGERED', { automationName: 'Verdict vocabulary' }) },
  };
}

/* The field-evidence set (skill v1.4 §4c — every class observed on the certified
 * deployed build), one scenario:
 *   - the SILENT-SKIP run: COMPLETED, actionCount 2 / commandCount 0 / actions[]
 *     empty (lawful Doc 07 §3.9 per-target skips) — must never read as success;
 *   - the NULL-NAME run: automationName/trigger.type null (prior-instance runs);
 *   - the REHYDRATED-AVAILABLE entity: API says AVAILABLE from rehydrated history
 *     while the last evidence is days old (why the surface renders evidence-with-age);
 *   - the HONEST-UNKNOWN entity: no report since restart (calm, resolves on first report);
 *   - DP-B2 "ran fine": NEVER_TRIGGERED + non-null lastRelevantRunId pointing at
 *     the silent-skip run — the composed lie the run page then untangles honestly.
 */
function buildFieldEvidence(): MockDataset {
  // Silent-skip run — the actionCount-vs-actions[] disagreement IS the tell.
  const skip = makeChain('run_fe_skip', {
    automationId: 'auto_fe',
    automationName: 'Away lights',
    minAgo: 12,
  });
  skip.actions = [];
  skip.outcome = { status: 'COMPLETED', reason: null, durationMs: 41, actionCount: 2, commandCount: 0 };

  // Null-name run (prior-instance class): name + trigger.type null ON THE WIRE.
  const nullName = makeChain('run_fe_nullname', { minAgo: 2880 });
  nullName.automationName = null;
  nullName.trigger.type = null;
  const nullNameRun = makeRun('run_fe_nullname', { minAgo: 2880 });
  nullNameRun.automationName = null;

  const entities: EntitySummary[] = [
    ...base.entities,
    // Physically off-network, yet AVAILABLE from rehydrated history (AVAIL-RECONCILE).
    { entityId: 'ent_office_bulb', availability: 'AVAILABLE', stale: true },
    // Honest UNKNOWN since restart — no fresh report yet.
    { entityId: 'ent_porch_contact', availability: 'UNKNOWN', stale: false },
  ];
  const entityState: Record<string, EntityState> = {
    ...base.entityState,
    ent_office_bulb: {
      entityId: 'ent_office_bulb',
      availability: 'AVAILABLE',
      attributes: { power: { t: 'BOOL', v: true } },
      stateVersion: 44,
      lastChanged: iso(2760),
      lastUpdated: iso(2760),
      lastReported: iso(2760), // ~2 days of silence behind an "Available" flag
      stale: true,
      staleAfter: iso(2640),
    },
    ent_porch_contact: {
      entityId: 'ent_porch_contact',
      availability: 'UNKNOWN',
      attributes: {},
      stateVersion: 1,
      lastChanged: null,
      lastUpdated: null,
      lastReported: null,
      stale: false,
      staleAfter: null,
    },
  };

  return {
    ...defaultDataset,
    entities,
    entityState,
    automations: [makeAutomation('auto_fe', 'Away lights', { lastRunId: 'run_fe_skip' })],
    runs: [makeRun('run_fe_skip', { automationId: 'auto_fe', automationName: 'Away lights', minAgo: 12 }), nullNameRun],
    causalChains: { run_fe_skip: skip, run_fe_nullname: nullName },
    nonFiring: {
      // DP-B2 wire shape for a "clean" COMPLETED run — which here was a do-nothing
      // run: the verdict alone would read "ran and confirmed"; the linked run page
      // is where the honest story lives.
      auto_fe: makeNonFiring('auto_fe', 'NEVER_TRIGGERED', {
        automationName: 'Away lights',
        lastRelevantRunId: 'run_fe_skip',
        explanation: 'It ran 12 minutes ago and reported no problem.',
      }),
    },
  };
}

/* The live-fleet mirror (post-04P): one entity per deployed class — light ·
 * occupancy · switch · temp/hum/battery · contact · battery-only. Attribute keys
 * are SOURCE-DERIVED (canonical schema keys temperature_c / humidity_pct from the
 * W2 handlers; brightness 0–254 canonical + the DERIVED brightness_percent
 * decoration, MaterializedStateQueryService.java:113). A live probe of the Pi's
 * read-API was not reachable from this session — re-verify shapes at the first
 * live run (noted in the lane return).
 */
function buildLiveFleet(): MockDataset {
  const mk = (
    entityId: string,
    availability: EntitySummary['availability'],
    attrs: EntityState['attributes'],
    minAgo: number,
    stale = false,
  ): EntityState => ({
    entityId,
    availability,
    attributes: attrs,
    stateVersion: 3,
    lastChanged: iso(minAgo),
    lastUpdated: iso(minAgo),
    lastReported: iso(minAgo),
    stale,
    staleAfter: null,
  });
  const entityState: Record<string, EntityState> = {
    ent_hue_light: mk('ent_hue_light', 'AVAILABLE', {
      power: { t: 'BOOL', v: true },
      brightness: { t: 'NUMBER', v: 209 }, // canonical 0–254 level
      brightness_percent: { t: 'PERCENT', v: 82 }, // DERIVED at query time — the % the UI shows
    }, 3),
    ent_snzb03p_motion: mk('ent_snzb03p_motion', 'AVAILABLE', { occupancy: { t: 'BOOL', v: false }, battery: { t: 'PERCENT', v: 97 } }, 6),
    ent_s31_switch: mk('ent_s31_switch', 'AVAILABLE', { power: { t: 'BOOL', v: true } }, 1),
    ent_snzb02p_climate: mk('ent_snzb02p_climate', 'AVAILABLE', {
      temperature_c: { t: 'NUMBER', v: 23.41 },
      humidity_pct: { t: 'NUMBER', v: 47.2 },
      battery: { t: 'PERCENT', v: 100 },
    }, 9),
    ent_snzb04p_contact: mk('ent_snzb04p_contact', 'AVAILABLE', { contact: { t: 'BOOL', v: true }, battery: { t: 'PERCENT', v: 100 } }, 14),
    ent_snzb01p_button: mk('ent_snzb01p_button', 'AVAILABLE', { battery: { t: 'PERCENT', v: 100 } }, 45),
  };
  const entities: EntitySummary[] = Object.values(entityState).map((s) => ({
    entityId: s.entityId,
    availability: s.availability,
    stale: s.stale,
  }));
  return { ...defaultDataset, entities, entityState, entityDetail: {} };
}

// Connected but empty — exercises the "empty as teaching", never a blank panel.
function buildEmpty(): MockDataset {
  return {
    entities: [],
    entityDetail: {},
    entityState: {},
    // Wire-faithful A4/A5 (v1.1.1): an empty home still carries the ruled additive
    // extras — 0 entities, ready, and the platform subscribers all LIVE.
    projection: { mode: 'LIVE', viewPosition: base.projection.viewPosition, lagEvents: 0, projectionVersion: 5, entityCount: 0, ready: true },
    dlq: { depth: 0, parkedSubscribers: [], subscribers: base.dlq.subscribers },
    health: { phase: 'RUNNING', projection: { mode: 'LIVE', viewPosition: base.projection.viewPosition, lagEvents: 0 }, dlq: { depth: 0, parkedSubscribers: [] }, integrations: [] },
    automations: [],
    runs: [],
    causalChains: {},
    nonFiring: {},
    events: [],
  };
}

/* ---- The registry ---- */
export interface Scenario {
  id: string;
  label: string;
  group: 'Story' | 'Scale';
  blurb: string;
  build: () => MockDataset;
}

export const SCENARIOS: Scenario[] = [
  { id: 'default', label: 'Coherent home', group: 'Story', blurb: 'The baseline: motion→light confirmed, one honest unconfirmed, mixed origins.', build: () => defaultDataset },
  { id: 'all-outcomes', label: 'All outcomes', group: 'Story', blurb: 'One automation, every command outcome + run status — confirmed, sent-not-confirmed, failed, skipped, cancelled, interrupted.', build: buildAllOutcomes },
  { id: 'cascade', label: 'Cascade', group: 'Story', blurb: 'A run that triggered another — the child links back to “what triggered this”.', build: buildCascade },
  { id: 'all-verdicts', label: 'All “why not?” verdicts', group: 'Story', blurb: 'Condition-not-met, never-triggered, acted-but-unconfirmed, disabled.', build: buildAllVerdicts },
  { id: 'e5-confirmation', label: 'Confirmation, measured', group: 'Story', blurb: 'AMD-97 honest states at measured timing: color confirms slowly (flips live ~8s in), idempotent confirmed-from-cache, effect honestly unconfirmed, superseded expiry.', build: buildE5Confirmation },
  { id: 'verdict-vocabulary', label: 'The ten verdicts', group: 'Story', blurb: 'Every command_result outcome as it reaches the wire today — the flattened FAILEDs carry the recorded reason, and the honest layer renders superseded/expired as intent-change, not failure.', build: buildVerdictVocabulary },
  { id: 'field-evidence', label: 'Field evidence', group: 'Story', blurb: 'The silent-skip do-nothing run, the null-name prior-instance run, rehydrated “Available” with days-old evidence, and honest UNKNOWN since restart.', build: buildFieldEvidence },
  { id: 'live-fleet', label: 'Live fleet mirror', group: 'Story', blurb: 'One entity per deployed device class with canonical attribute keys — including brightness level 0–254 plus the hub-derived percent.', build: buildLiveFleet },
  { id: 'all-origins', label: 'All event origins', group: 'Story', blurb: 'Automation, device, you, external, and the honest UNKNOWN.', build: buildAllOrigins },
  { id: 'large', label: 'Large (300 runs · 500 events)', group: 'Scale', blurb: 'Forces list virtualization + a render budget.', build: buildLarge },
  { id: 'empty', label: 'Empty (fresh install)', group: 'Scale', blurb: 'Connected but nothing has happened yet — empty states that teach.', build: buildEmpty },
];

export const DEFAULT_SCENARIO_ID = 'default';

export function resolveScenario(id: string): MockDataset {
  const s = SCENARIOS.find((x) => x.id === id);
  return (s ?? SCENARIOS[0]!).build();
}
