/*
 * HomeSynapse — Mock SCENARIOS (T1.2, the pre-hardware sprint keystone).
 * ---------------------------------------------------------------------------
 * A scenario system that can produce EVERY condition the FROZEN v1.1 contract allows, on
 * demand — so the mock demo is complete now, FE-4 can verify every state on realistic data,
 * and live-integration (FE-1) meets no shape it hasn't already faced. Every dataset is shaped
 * by the same contract types the real transport returns; contract.test.ts validates them.
 *
 * Two orthogonal dimensions (see mockState.ts): a DATA scenario (the story the data tells) and
 * a TRANSPORT condition (replaying / offline / slow / 401 / 403 / etag). This file owns the data.
 *
 * Bundle note: variant datasets are built lazily (`build()`), and large lists are GENERATED by
 * code (not materialized literals), so the static footprint stays small — mock ships in the
 * demo/website-embed builds (sprint §T1.2), and we keep the 100 KB budget honest.
 */
import type {
  AutomationSummary,
  CausalAction,
  CausalChain,
  CausalCondition,
  ConsolidatedHealth,
  DlqStatus,
  EntityDetail,
  EntityState,
  EntitySummary,
  EventSummary,
  NonFiringExplanation,
  Origin,
  ProjectionStatus,
  RunStatus,
  ActionOutcome,
  NonFiringVerdict,
  RunSummary,
} from '../contract';
import * as base from './mockData';

/** The full fixture bundle a scenario serves. Mirrors the endpoints in mockTransport. */
export interface MockDataset {
  entities: EntitySummary[];
  entityDetail: Record<string, EntityDetail>;
  entityState: Record<string, EntityState>;
  projection: ProjectionStatus;
  dlq: DlqStatus;
  health: ConsolidatedHealth;
  automations: AutomationSummary[];
  runs: RunSummary[];
  causalChains: Record<string, CausalChain>;
  nonFiring: Record<string, NonFiringExplanation>;
  events: EventSummary[];
}

const now = Date.now();
const iso = (minAgo: number) => new Date(now - minAgo * 60_000).toISOString();
let evSeq = 90_000;
const nextEvVp = () => ++evSeq;

/* ---- Contract-shaped factories (defaults + overrides; keep every field on-contract) ---- */

const ACTION_REASON: Record<ActionOutcome, string | null> = {
  CONFIRMED: null,
  DISPATCHED: null,
  UNCONFIRMED: 'No state_confirmed within the 5s timeout',
  FAILED: 'Device unreachable — the command was rejected',
  SKIPPED: 'A condition was not met',
};

function makeAction(outcome: ActionOutcome, over: Partial<CausalAction> = {}): CausalAction {
  return {
    type: 'device_command',
    targetRef: { type: 'ENTITY', id: 'ent_hallway_light' },
    command: 'turn_on',
    params: outcome === 'SKIPPED' ? {} : { brightness: 82 },
    outcome,
    reason: ACTION_REASON[outcome],
    ...over,
  };
}

function makeCondition(result: boolean, over: Partial<CausalCondition> = {}): CausalCondition {
  return {
    expression: 'time is after sunset',
    evaluated: true,
    result,
    observedState: [{ entityId: 'sys_sun', attribute: 'elevation', value: result ? '-6.2°' : '+24.7°' }],
    ...over,
  };
}

interface ChainOpts {
  automationId?: string;
  automationName?: string;
  outcome?: ActionOutcome;
  status?: RunStatus;
  conditionResult?: boolean;
  parentRunId?: string | null;
  depth?: number;
  triggerId?: string;
  targetId?: string;
  terminalReason?: string | null;
  durationMs?: number;
  minAgo?: number;
}

function makeChain(runId: string, o: ChainOpts = {}): CausalChain {
  const status = o.status ?? 'COMPLETED';
  const outcome = o.outcome ?? (status === 'SKIPPED' ? 'SKIPPED' : 'CONFIRMED');
  const condResult = o.conditionResult ?? status !== 'SKIPPED';
  return {
    runId,
    automationId: o.automationId ?? 'auto_demo',
    automationName: o.automationName ?? 'Demo automation',
    trigger: {
      type: 'state_changed',
      subjectRef: { type: 'ENTITY', id: o.triggerId ?? 'ent_hallway_motion' },
      matchedAt: iso(o.minAgo ?? 2),
      firingValue: 'motion = detected',
    },
    conditions: [makeCondition(condResult)],
    actions: [makeAction(outcome, { targetRef: { type: 'ENTITY', id: o.targetId ?? 'ent_hallway_light' } })],
    outcome: {
      status,
      reason: o.terminalReason ?? null,
      durationMs: o.durationMs ?? 412,
      actionCount: 1,
      commandCount: outcome === 'SKIPPED' ? 0 : 1,
    },
    cascade: { parentRunId: o.parentRunId ?? null, depth: o.depth ?? 0 },
  };
}

function makeRun(runId: string, o: Partial<RunSummary> & { minAgo?: number } = {}): RunSummary {
  return {
    runId,
    automationId: o.automationId ?? 'auto_demo',
    automationName: o.automationName ?? 'Demo automation',
    triggeredAt: o.triggeredAt ?? iso(o.minAgo ?? 2),
    status: o.status ?? 'COMPLETED',
    terminalReason: o.terminalReason ?? null,
  };
}

function makeEvent(eventId: string, origin: Origin, over: Partial<EventSummary> = {}): EventSummary {
  const SUMMARY: Record<Origin, string> = {
    AUTOMATION: 'Hallway Light turned on',
    DEVICE: 'Hallway Motion detected motion',
    USER: 'Living Room Lamp turned off from the app',
    EXTERNAL: 'Kitchen Light changed outside the system',
    UNKNOWN: 'Kitchen Light reported a brightness change',
  };
  return {
    eventId,
    type: 'state_changed',
    category: 'STATE',
    occurredAt: iso(1),
    viewPosition: nextEvVp(),
    subjectRef: { type: 'ENTITY', id: 'ent_hallway_light' },
    correlationId: 'cor_demo',
    causationId: null,
    origin,
    summary: SUMMARY[origin],
    ...over,
  };
}

function makeNonFiring(
  automationId: string,
  verdict: NonFiringVerdict,
  over: Partial<NonFiringExplanation> = {},
): NonFiringExplanation {
  const EXPLAIN: Record<NonFiringVerdict, string> = {
    CONDITION_NOT_MET: 'It did not run because it was before sunset when the trigger fired.',
    NEVER_TRIGGERED: 'Nothing set it off. The trigger has not matched in the last hour.',
    ACTED_BUT_UNCONFIRMED: 'It ran, but the device never confirmed it acted — it may be slow or briefly offline.',
    DISABLED: 'This automation is turned off, so it cannot run.',
  };
  return {
    automationId,
    automationName: over.automationName ?? 'Demo automation',
    enabled: verdict !== 'DISABLED',
    verdict,
    lastRelevantRunId: verdict === 'CONDITION_NOT_MET' || verdict === 'ACTED_BUT_UNCONFIRMED' ? 'run_demo_ref' : null,
    explanation: EXPLAIN[verdict],
    triggerSummary: 'This runs when Hallway Motion detects motion, after sunset.',
    lastEvaluation:
      verdict === 'CONDITION_NOT_MET'
        ? { at: iso(30), conditionsResult: 'after sunset = false' }
        : { at: null, conditionsResult: null },
    ...over,
  };
}

function makeAutomation(automationId: string, name: string, over: Partial<AutomationSummary> = {}): AutomationSummary {
  return {
    automationId,
    name,
    enabled: true,
    components: [
      { type: 'trigger', summary: 'When Hallway Motion detects motion' },
      { type: 'condition', summary: 'Only after sunset' },
      { type: 'action', summary: 'Turn on Hallway Light' },
    ],
    lastRunId: null,
    ...over,
  };
}

/* ---- The default coherent home (the current fixtures) ---- */
export const defaultDataset: MockDataset = {
  entities: base.entities,
  entityDetail: base.entityDetail,
  entityState: base.entityState,
  projection: base.projection,
  dlq: base.dlq,
  health: base.health,
  automations: base.automations,
  runs: base.runs,
  causalChains: base.causalChains,
  nonFiring: base.nonFiring,
  events: base.events,
};

/* ---- Variant builders ---- */

// Every command outcome + every run status, one automation, as a run list you can click through.
function buildAllOutcomes(): MockDataset {
  const A = { automationId: 'auto_demo', automationName: 'Demo automation' };
  const specs: { id: string; outcome: ActionOutcome; status: RunStatus; reason?: string | null; min: number }[] = [
    { id: 'run_oc_confirmed', outcome: 'CONFIRMED', status: 'COMPLETED', min: 2 },
    { id: 'run_oc_dispatched', outcome: 'DISPATCHED', status: 'COMPLETED', reason: 'Command sent; awaiting confirmation', min: 4 },
    { id: 'run_oc_unconfirmed', outcome: 'UNCONFIRMED', status: 'COMPLETED', reason: 'Action sent; device did not confirm within 5s', min: 9 },
    { id: 'run_oc_failed', outcome: 'FAILED', status: 'FAILED', reason: 'Device unreachable', min: 22 },
    { id: 'run_oc_skipped', outcome: 'SKIPPED', status: 'SKIPPED', reason: 'Condition not met: before sunset', min: 40 },
    { id: 'run_oc_cancelled', outcome: 'SKIPPED', status: 'CANCELLED', reason: 'Superseded by a newer run', min: 70 },
    { id: 'run_oc_interrupted', outcome: 'FAILED', status: 'INTERRUPTED', reason: 'System restarted mid-run', min: 130 },
  ];
  const runs = specs.map((s) => makeRun(s.id, { ...A, status: s.status, terminalReason: s.reason ?? null, minAgo: s.min }));
  const causalChains: Record<string, CausalChain> = {};
  for (const s of specs) {
    causalChains[s.id] = makeChain(s.id, {
      ...A,
      outcome: s.outcome,
      status: s.status,
      conditionResult: s.status !== 'SKIPPED',
      terminalReason: s.reason ?? null,
      minAgo: s.min,
    });
  }
  return {
    ...defaultDataset,
    automations: [makeAutomation('auto_demo', 'Demo automation', { lastRunId: 'run_oc_confirmed' })],
    runs,
    causalChains,
    nonFiring: { auto_demo: makeNonFiring('auto_demo', 'NEVER_TRIGGERED', { automationName: 'Demo automation' }) },
  };
}

// A parent → child cascade: one run triggers another; the child links back to its cause.
function buildCascade(): MockDataset {
  const parent = makeChain('run_casc_parent', {
    automationId: 'auto_sunset',
    automationName: 'Sunset Scene',
    triggerId: 'sys_sun',
    targetId: 'ent_livingroom_lamp',
    minAgo: 3,
  });
  parent.trigger = { type: 'time', subjectRef: { type: 'SYSTEM', id: 'sys_sun' }, matchedAt: iso(3), firingValue: 'sun set' };
  const child = makeChain('run_casc_child', {
    automationId: 'auto_evening_hallway',
    automationName: 'Evening Hallway Light',
    parentRunId: 'run_casc_parent',
    depth: 1,
    minAgo: 3,
  });
  return {
    ...defaultDataset,
    automations: [
      makeAutomation('auto_sunset', 'Sunset Scene', { lastRunId: 'run_casc_parent' }),
      makeAutomation('auto_evening_hallway', 'Evening Hallway Light', { lastRunId: 'run_casc_child' }),
    ],
    runs: [
      makeRun('run_casc_child', { automationId: 'auto_evening_hallway', automationName: 'Evening Hallway Light', minAgo: 3 }),
      makeRun('run_casc_parent', { automationId: 'auto_sunset', automationName: 'Sunset Scene', minAgo: 3 }),
    ],
    causalChains: { run_casc_parent: parent, run_casc_child: child },
  };
}

// All four "why didn't it fire?" verdicts, one automation each.
function buildAllVerdicts(): MockDataset {
  const defs: { id: string; name: string; verdict: NonFiringVerdict }[] = [
    { id: 'auto_v_condition', name: 'Front Door Welcome', verdict: 'CONDITION_NOT_MET' },
    { id: 'auto_v_never', name: 'Evening Hallway Light', verdict: 'NEVER_TRIGGERED' },
    { id: 'auto_v_acted', name: 'Bedtime Lights Off', verdict: 'ACTED_BUT_UNCONFIRMED' },
    { id: 'auto_v_disabled', name: 'Bedroom Night Light', verdict: 'DISABLED' },
  ];
  const nonFiring: Record<string, NonFiringExplanation> = {};
  for (const d of defs) nonFiring[d.id] = makeNonFiring(d.id, d.verdict, { automationName: d.name });
  return {
    ...defaultDataset,
    automations: defs.map((d) => makeAutomation(d.id, d.name, { enabled: d.verdict !== 'DISABLED' })),
    nonFiring,
  };
}

// Every event origin, including the honest UNKNOWN (never a silent blank).
function buildAllOrigins(): MockDataset {
  const origins: Origin[] = ['AUTOMATION', 'DEVICE', 'USER', 'EXTERNAL', 'UNKNOWN'];
  return {
    ...defaultDataset,
    events: origins.map((o, i) => makeEvent(`evt_origin_${i}`, o, { occurredAt: iso(i + 1) })),
  };
}

// Hundreds of rows — the input that forces list virtualization (T2.3) and stresses render-at-scale.
function buildLarge(): MockDataset {
  const STATUSES: RunStatus[] = ['COMPLETED', 'FAILED', 'SKIPPED', 'CANCELLED', 'INTERRUPTED'];
  const OUTCOMES: ActionOutcome[] = ['CONFIRMED', 'DISPATCHED', 'UNCONFIRMED', 'FAILED', 'SKIPPED'];
  const ORIGINS: Origin[] = ['AUTOMATION', 'DEVICE', 'USER', 'EXTERNAL', 'UNKNOWN'];
  const runs: RunSummary[] = [];
  const causalChains: Record<string, CausalChain> = {};
  for (let i = 0; i < 300; i++) {
    const id = `run_lg_${String(i).padStart(4, '0')}`;
    const status = STATUSES[i % STATUSES.length]!;
    const outcome = OUTCOMES[i % OUTCOMES.length]!;
    runs.push(makeRun(id, { status, minAgo: i * 7 + 2, terminalReason: status === 'COMPLETED' ? null : `${status.toLowerCase()} (#${i})` }));
    causalChains[id] = makeChain(id, { outcome, status, minAgo: i * 7 + 2 });
  }
  const events: EventSummary[] = [];
  for (let i = 0; i < 500; i++) {
    events.push(makeEvent(`evt_lg_${String(i).padStart(4, '0')}`, ORIGINS[i % ORIGINS.length]!, { occurredAt: iso(i + 1) }));
  }
  return { ...defaultDataset, automations: [makeAutomation('auto_demo', 'Demo automation')], runs, causalChains, events };
}

// Connected but empty — exercises the "empty as teaching", never a blank panel.
function buildEmpty(): MockDataset {
  return {
    entities: [],
    entityDetail: {},
    entityState: {},
    projection: { mode: 'LIVE', viewPosition: base.projection.viewPosition, lagEvents: 0, projectionVersion: 5 },
    dlq: { depth: 0, parkedSubscribers: [] },
    health: { phase: 'RUNNING', projection: { mode: 'LIVE', viewPosition: base.projection.viewPosition, lagEvents: 0 }, dlq: { depth: 0, parkedSubscribers: [] }, integrations: [] },
    automations: [],
    runs: [],
    causalChains: {},
    nonFiring: {},
    events: [],
  };
}

/* ---- The registry ---- */
export interface Scenario {
  id: string;
  label: string;
  group: 'Story' | 'Scale';
  blurb: string;
  build: () => MockDataset;
}

export const SCENARIOS: Scenario[] = [
  { id: 'default', label: 'Coherent home', group: 'Story', blurb: 'The baseline: motion→light confirmed, one honest unconfirmed, mixed origins.', build: () => defaultDataset },
  { id: 'all-outcomes', label: 'All outcomes', group: 'Story', blurb: 'One automation, every command outcome + run status — confirmed, sent-not-confirmed, failed, skipped, cancelled, interrupted.', build: buildAllOutcomes },
  { id: 'cascade', label: 'Cascade', group: 'Story', blurb: 'A run that triggered another — the child links back to “what triggered this”.', build: buildCascade },
  { id: 'all-verdicts', label: 'All “why not?” verdicts', group: 'Story', blurb: 'Condition-not-met, never-triggered, acted-but-unconfirmed, disabled.', build: buildAllVerdicts },
  { id: 'all-origins', label: 'All event origins', group: 'Story', blurb: 'Automation, device, you, external, and the honest UNKNOWN.', build: buildAllOrigins },
  { id: 'large', label: 'Large (300 runs · 500 events)', group: 'Scale', blurb: 'Forces list virtualization + a render budget.', build: buildLarge },
  { id: 'empty', label: 'Empty (fresh install)', group: 'Scale', blurb: 'Connected but nothing has happened yet — empty states that teach.', build: buildEmpty },
];

export const DEFAULT_SCENARIO_ID = 'default';

export function resolveScenario(id: string): MockDataset {
  const s = SCENARIOS.find((x) => x.id === id);
  return (s ?? SCENARIOS[0]!).build();
}
