/*
 * HomeSynapse Core
 * Copyright (c) 2026 NexSys. All rights reserved.
 */
package com.homesynapse.api.rest;

/**
 * Structured HTTP error thrown by REST API middleware and validators.
 *
 * <p>The error handling layer catches {@code ApiException} and serializes the
 * contained {@link ProblemDetail} as {@code application/problem+json} (Doc 09 §3.8).
 * This provides a uniform error response format for all REST API-layer errors.</p>
 *
 * <p>{@code ApiException} handles errors generated by the REST API layer itself —
 * authentication failures, rate limiting, parameter validation, idempotency
 * conflicts. This is distinct from {@link ProblemDetailMapper}, which maps
 * exceptions from downstream subsystems (e.g., {@code HomeSynapseException}
 * subtypes from the event model, {@code ConcurrentModificationException} from
 * the configuration write path) to {@link ProblemDetail} responses.</p>
 *
 * <p>Thread-safe (immutable after construction).</p>
 *
 * @see ProblemDetail
 * @see ProblemDetailMapper
 * @see ProblemType
 * @see <a href="Doc 09 §3.8">Error Response Model</a>
 */
public class ApiException extends RuntimeException {

    @java.io.Serial
    private static final long serialVersionUID = 1L;

    private final transient ProblemDetail problemDetail;

    /**
     * Creates a new API exception with the given structured error detail.
     *
     * @param problemDetail the structured error to return as the HTTP response body,
     *                      never {@code null}
     */
    public ApiException(ProblemDetail problemDetail) {
        super(problemDetail.detail());
        this.problemDetail = problemDetail;
    }

    /**
     * Creates a new API exception with the given structured error detail and cause.
     *
     * @param problemDetail the structured error to return as the HTTP response body,
     *                      never {@code null}
     * @param cause         the underlying cause of this exception
     */
    public ApiException(ProblemDetail problemDetail, Throwable cause) {
        super(problemDetail.detail(), cause);
        this.problemDetail = problemDetail;
    }

    /**
     * Returns the structured RFC 9457 Problem Detail for this error.
     *
     * <p>The returned {@link ProblemDetail} contains all information needed to
     * construct the {@code application/problem+json} HTTP response body.</p>
     *
     * @return the problem detail, never {@code null}
     */
    public ProblemDetail problemDetail() {
        return problemDetail;
    }
}
