/*
 * HomeSynapse Core
 * Copyright (c) 2026 NexSys. All rights reserved.
 */
package com.homesynapse.api.rest;

/**
 * Maps internal exceptions from downstream subsystems to RFC 9457 Problem Detail responses.
 *
 * <p>This interface handles exceptions that are NOT {@link ApiException} (Doc 09 §3.8).
 * {@code ApiException} handles errors generated by the REST API layer itself
 * (authentication failures, rate limiting, parameter validation). This mapper handles
 * everything else — exceptions from the event model, device model, state store,
 * automation engine, and other internal subsystems.</p>
 *
 * <p>Examples of mapped exceptions:</p>
 * <ul>
 *   <li>{@code HomeSynapseException} subtypes (e.g., {@code EntityNotFoundException},
 *       {@code CapabilityMismatchException}) — mapped to specific
 *       {@link ProblemType} values.</li>
 *   <li>{@code ConcurrentModificationException} from the configuration write path —
 *       mapped to an appropriate conflict response.</li>
 *   <li>Unexpected {@code RuntimeException} instances — mapped to
 *       {@link ProblemType#INTERNAL_ERROR} (500) with a generic detail message.</li>
 * </ul>
 *
 * <p>Stack traces are NEVER included in API responses (Doc 09 §12.4). The
 * {@code correlationId} links the error response to server-side structured log
 * entries for diagnosis.</p>
 *
 * <p>Thread-safe.</p>
 *
 * @see ProblemDetail
 * @see ApiException
 * @see ProblemType
 * @see <a href="Doc 09 §3.8">Error Response Model</a>
 */
public interface ProblemDetailMapper {

    /**
     * Maps an internal exception to an RFC 9457 Problem Detail response.
     *
     * <p>For unrecognized exceptions, returns {@link ProblemType#INTERNAL_ERROR}
     * (500) with a generic detail message. The original exception's message is
     * logged server-side but not exposed in the API response.</p>
     *
     * @param exception     the internal exception to map, never {@code null}
     * @param correlationId the request-scoped correlation ID for log linkage,
     *                      never {@code null}
     * @param requestPath   the request path that triggered the error,
     *                      never {@code null}
     * @return the mapped Problem Detail, never {@code null}
     */
    ProblemDetail map(Exception exception, String correlationId, String requestPath);
}
