/*
 * HomeSynapse Core
 * Copyright (c) 2026 NexSys. All rights reserved.
 */
package com.homesynapse.config;

import java.nio.file.Path;
import java.time.Clock;

/**
 * Per-scope key-management gateway (Doc 15 §3.5/§4.2, M6.2) — the single
 * owner of the machine-local root key, the derived per-scope KEKs, the
 * wrapped per-scope DEKs, and the {@code scope_keys} store.
 *
 * <h2>Key hierarchy (Doc 15 §4.2)</h2>
 *
 * <ul>
 *   <li><strong>Root key</strong> — 256-bit, generated by
 *       {@code SecureRandom} and stored at {@code ${config_dir}/.root-key}
 *       (POSIX {@code 0400}, best-effort on non-POSIX filesystems).
 *       Created lazily on first need: a zero-config install with no
 *       secrets never creates it (INV-CE-02). Never logged, never carried
 *       in events (Doc 06 §12.3 / LTD-15).</li>
 *   <li><strong>Scope KEK</strong> — re-derived on demand as
 *       {@code HKDF-SHA256(root, "scope:" + scopeId)} (RFC 5869), cached
 *       per active scope, never stored.</li>
 *   <li><strong>Scope DEK</strong> — 256-bit {@code SecureRandom},
 *       wrapped by the scope KEK with AES-256-GCM, persisted in the
 *       config-side {@code scope_keys.json} store with {@code keyVersion}
 *       starting at 1. The store file is plaintext-correct: every DEK in
 *       it is wrapped ciphertext, unreadable without the root key.</li>
 * </ul>
 *
 * <h2>IV discipline</h2>
 *
 * <p>{@link #encrypt} uses a fresh random 96-bit GCM IV per call. Random
 * IVs are correct for this manager's M6.2 consumers (full-file rewrites of
 * {@code secrets.enc} and similar low-volume payloads — collision risk at
 * occasional-write volume is negligible). The M6.3 per-event at-rest write
 * path requires the OR-M6-NONCE counter-nonce discipline instead (Doc 15
 * §3.4 — random nonces hit the GCM birthday bound at event volume); do not
 * generalize this manager's random-IV model to that path.</p>
 *
 * <h2>Unreadability (Doc 15 §8.2 contract-freeze gate)</h2>
 *
 * <p>{@link #decrypt} of a {@code (scopeId, keyVersion)} pair that is
 * absent from the store or marked {@code destroyedAt} throws — destroying
 * a scope key renders that scope's ciphertext permanently unreadable
 * (crypto-shred, INV-PD-07). The shred <em>operation</em> that sets
 * {@code destroyedAt} is post-MVP; M6.2 ships the unreadability property
 * only.</p>
 *
 * <h2>Module placement (Doc 15 §3.8 / CARRY 1)</h2>
 *
 * <p>This type deliberately does NOT implement the persistence-exported
 * {@code PayloadCipher} seam — that would force a {@code config →
 * persistence} module edge. The composition root ({@code
 * com.homesynapse.app.Main}) wraps this manager in a thin adapter and
 * threads it through the lifecycle module to persistence (the AMD-45
 * injection-at-the-composition-root discipline; zero new module edges).
 * The stale Doc 15 §8.1 row saying otherwise is a parked currency nit —
 * §3.8 governs.</p>
 *
 * <h2>Thread safety</h2>
 *
 * <p>Implementations are thread-safe. Store mutations serialize on a
 * {@code ReentrantLock} (LTD-11); {@code javax.crypto.Cipher} instances
 * are per-call, never shared.</p>
 *
 * @see ScopeCipherResult
 * @see ScopeKey
 * @see SecretStore
 */
public interface ScopeKeyManager {

    /**
     * Encrypts the plaintext under the scope's current DEK with
     * AES-256-GCM and a fresh random 96-bit IV.
     *
     * <p>Lazily creates the root key and the scope's version-1 DEK on the
     * scope's first encryption (DP-1/DP-4 — zero-config installs that
     * never encrypt never create key files, INV-CE-02).</p>
     *
     * <p>The argument and result arrays are NOT defensively copied — this
     * is a hot-path surface for trusted same-process callers.</p>
     *
     * @param scopeId   the encryption scope (e.g. {@code "config_secrets"});
     *                  never {@code null} or blank
     * @param plaintext the bytes to encrypt; never {@code null}
     * @return ciphertext (with the GCM tag appended), the IV used, and the
     *         DEK version that encrypted it; never {@code null}
     * @throws IllegalStateException if a key file is corrupt or the
     *         cryptographic operation fails
     */
    ScopeCipherResult encrypt(String scopeId, byte[] plaintext);

    /**
     * Encrypts an event payload under the scope's current DEK with
     * AES-256-GCM and a per-scope <strong>COUNTER</strong> nonce (Doc 15
     * §3.4, M6.3) — never a random IV (the GCM birthday bound is reached at
     * event volume).
     *
     * <p>The per-scope 96-bit nonce is derived from a strictly monotonic
     * counter that is DURABLE and re-initialized from the persisted
     * high-water mark on boot, never from memory (OR-M6-NONCE). The counter
     * high-water mark is persisted (fsync) <em>ahead of</em> returning the
     * nonce, so a crash after this call but before the persistence INSERT can
     * only leave a gap, never a reuse.</p>
     *
     * <p>This is the M6.3 payload path, deliberately distinct from
     * {@link #encrypt} — see the {@code <h2>IV discipline</h2>} note above:
     * the random-IV {@code encrypt} is the M6.2 secrets path and must NOT be
     * generalized here, and this counter path must NOT be cargo-culted onto
     * secrets. {@link #decrypt} round-trips either path's ciphertext
     * unchanged.</p>
     *
     * <p>Lazily creates the root key and the scope's version-1 DEK on the
     * scope's first encryption, exactly like {@link #encrypt} (INV-CE-02).
     * The argument and result arrays are NOT defensively copied.</p>
     *
     * @param scopeId   an encrypted scope (e.g. {@code "identity"},
     *                  {@code "presence_personal"}); never {@code null}
     *                  or blank
     * @param plaintext the serialized payload bytes; never {@code null}
     * @return ciphertext (GCM tag appended), the counter nonce as the
     *         {@code iv}, and the DEK version; never {@code null}
     * @throws IllegalStateException if a key file is corrupt, the
     *         cryptographic operation fails, or the scope is already bound to
     *         the random-IV {@link #encrypt} construction (F3 — one nonce
     *         construction per scope)
     */
    ScopeCipherResult encryptPayload(String scopeId, byte[] plaintext);

    /**
     * Counter-nonce payload encryption (as {@link #encryptPayload(String, byte[])})
     * that additionally binds {@code aad} as AES-GCM additional authenticated
     * data (AB-4 F1) — bound into the tag but not encrypted. The persistence
     * write path uses it to bind the 1-byte at-rest envelope version
     * discriminator (Doc 15 §4.1) so the version is downgrade-resistant; the
     * version byte itself is framed in the persistence envelope codec.
     *
     * @param scopeId   an encrypted scope; never {@code null} or blank
     * @param plaintext the serialized payload bytes; never {@code null}
     * @param aad       additional authenticated data bound into the GCM tag
     *                  but not encrypted; never {@code null}, may be empty to
     *                  bind nothing
     * @return ciphertext (GCM tag appended), the counter nonce, and the DEK
     *         version; never {@code null}
     * @throws IllegalStateException if a key file is corrupt, the cryptographic
     *         operation fails, or the scope is already bound to the random-IV
     *         construction (F3)
     */
    ScopeCipherResult encryptPayload(String scopeId, byte[] plaintext, byte[] aad);

    /**
     * Decrypts ciphertext produced by {@link #encrypt} or
     * {@link #encryptPayload} under the named scope and DEK version.
     *
     * <p>The argument and result arrays are NOT defensively copied.</p>
     *
     * @param scopeId    the encryption scope; never {@code null} or blank
     * @param keyVersion the DEK version that encrypted the ciphertext
     * @param ciphertext the ciphertext with the GCM tag appended;
     *                   never {@code null}
     * @param iv         the 96-bit IV the ciphertext was encrypted with;
     *                   never {@code null}
     * @return the plaintext; never {@code null}
     * @throws IllegalArgumentException if no {@code (scopeId, keyVersion)}
     *         entry exists in the store, or the entry is marked
     *         {@code destroyedAt} — the ciphertext is permanently
     *         unreadable (the Doc 15 §8.2 unreadability property)
     * @throws IllegalStateException if GCM authentication fails (wrong
     *         scope, wrong key, or tampered ciphertext) or a key file is
     *         corrupt
     */
    byte[] decrypt(String scopeId, int keyVersion, byte[] ciphertext, byte[] iv);

    /**
     * Decrypts ciphertext (as {@link #decrypt(String, int, byte[], byte[])})
     * that additionally bound {@code aad} as AES-GCM additional authenticated
     * data at encrypt time (AB-4 F1). The {@code aad} MUST equal the encrypt-side
     * value byte-for-byte or GCM authentication fails — this is what makes the
     * bound envelope version downgrade-resistant.
     *
     * @param scopeId    the encryption scope; never {@code null} or blank
     * @param keyVersion the DEK version that encrypted the ciphertext
     * @param ciphertext the ciphertext with the GCM tag appended;
     *                   never {@code null}
     * @param iv         the 96-bit IV; never {@code null}
     * @param aad        the additional authenticated data bound at encrypt
     *                   time; never {@code null}, may be empty
     * @return the plaintext; never {@code null}
     * @throws IllegalArgumentException if no {@code (scopeId, keyVersion)}
     *         entry exists, or it is marked {@code destroyedAt}
     * @throws IllegalStateException if GCM authentication fails (wrong scope,
     *         wrong key, tampered ciphertext, or mismatched {@code aad}) or a
     *         key file is corrupt
     */
    byte[] decrypt(String scopeId, int keyVersion, byte[] ciphertext, byte[] iv,
                   byte[] aad);

    /**
     * Creates the standard manager rooted at the injected configuration
     * directory (the DEC-M3-16 public-gateway pattern — the implementation
     * class stays package-private).
     *
     * <p>Construction touches no files; the root key and the store are
     * created lazily on first {@link #encrypt} (INV-CE-02).</p>
     *
     * @param configDir the resolved configuration directory, injected as a
     *                  {@code Path} ([AMD-71-A] — no config→platform
     *                  module edge); never {@code null}
     * @param clock     time source for {@link ScopeKey#createdAt()} stamps;
     *                  never {@code null}
     * @return a new manager; never {@code null}
     */
    static ScopeKeyManager create(Path configDir, Clock clock) {
        return new StandardScopeKeyManager(configDir, clock);
    }
}
