/*
 * HomeSynapse Core
 * Copyright (c) 2026 NexSys. All rights reserved.
 */
package com.homesynapse.event;

import java.time.Instant;
import java.util.Objects;

/**
 * Bundles all caller-provided metadata for event publication via
 * {@link EventPublisher}.
 *
 * <p>An {@code EventDraft} captures the fields that the <em>caller</em> supplies
 * when producing an event. The remaining envelope fields are assigned by the
 * {@link EventPublisher} at append time:</p>
 *
 * <ul>
 *   <li>{@code eventId} — generated by the publisher using
 *       {@link com.homesynapse.platform.identity.UlidFactory} (monotonic)</li>
 *   <li>{@code ingestTime} — system clock at append time</li>
 *   <li>{@code subjectSequence} — next monotonic sequence for the subject</li>
 *   <li>{@code globalPosition} — SQLite {@code rowid} assigned at insert</li>
 *   <li>{@code categories} — derived from a static {@code eventType}→category
 *       mapping maintained by the publisher (Doc 01 §4.1, §4.4)</li>
 * </ul>
 *
 * <p>The causal context ({@link CausalContext}) is <em>not</em> part of the draft
 * because it determines which {@link EventPublisher} method to call: callers pass
 * a pre-built {@code CausalContext} to {@link EventPublisher#publish(EventDraft, CausalContext)}
 * for derived events, or an actor reference to
 * {@link EventPublisher#publishRoot(EventDraft, com.homesynapse.platform.identity.Ulid)}
 * for root events. This two-method API enforces causality at compile time.</p>
 *
 * <p>This record is immutable and safe to share across threads.</p>
 *
 * @param eventType     dotted category key identifying the event's type per the taxonomy
 *                      (Doc 01 §4.3); never {@code null} or blank
 * @param schemaVersion positive integer identifying the payload schema version; always
 *                      {@code >= 1}
 * @param eventTime     when the real-world occurrence happened, as reported by the event
 *                      source; {@code null} if the source has no reliable clock
 * @param subjectRef    identifies the domain object this event is about; never {@code null}
 * @param priority      delivery urgency and retention tier; never {@code null}
 * @param origin        evidence-based classification of the event's source; never {@code null}
 * @param payload       the event-type-specific data; never {@code null}
 * @see EventPublisher
 * @see EventEnvelope
 */
public record EventDraft(
        String eventType,
        int schemaVersion,
        Instant eventTime,
        SubjectRef subjectRef,
        EventPriority priority,
        EventOrigin origin,
        DomainEvent payload
) {

    /**
     * Validates all draft fields according to their documented constraints.
     *
     * @throws NullPointerException     if {@code eventType}, {@code subjectRef},
     *                                  {@code priority}, {@code origin}, or
     *                                  {@code payload} is {@code null}
     * @throws IllegalArgumentException if {@code eventType} is blank or
     *                                  {@code schemaVersion} is less than 1
     */
    public EventDraft {
        Objects.requireNonNull(eventType, "eventType must not be null");
        Objects.requireNonNull(subjectRef, "subjectRef must not be null");
        Objects.requireNonNull(priority, "priority must not be null");
        Objects.requireNonNull(origin, "origin must not be null");
        Objects.requireNonNull(payload, "payload must not be null");

        if (eventType.isBlank()) {
            throw new IllegalArgumentException("eventType must not be blank");
        }
        if (schemaVersion < 1) {
            throw new IllegalArgumentException(
                    "schemaVersion must be >= 1, got " + schemaVersion);
        }
    }
}
