/*
 * HomeSynapse Core
 * Copyright (c) 2026 NexSys. All rights reserved.
 */
package com.homesynapse.event;

import java.time.Instant;
import java.util.List;
import java.util.Objects;

/**
 * Standard immutable wrapper for every event in the HomeSynapse domain event store.
 *
 * <p>The event envelope separates core infrastructure metadata (identity, ordering,
 * causality, classification) from event-type-specific data carried in the
 * {@link #payload()}. Envelope fields are owned and populated by the core event
 * infrastructure; integration-specific and domain-specific data lives exclusively
 * in the payload. This separation ensures that the Event Bus, State Store, and
 * subscription system can operate on any event without knowledge of its payload
 * structure.</p>
 *
 * <p>As a Java {@code record}, {@code EventEnvelope} is immutable and thread-safe.
 * The {@link #categories()} list is defensively copied via {@link List#copyOf(java.util.Collection)}
 * in the compact constructor to guarantee that no external mutation can affect the
 * envelope after construction.</p>
 *
 * @param eventId         globally unique, monotonically increasing identifier for this
 *                        event (LTD-04). Generated by the EventPublisher at append time
 *                        using {@link com.homesynapse.platform.identity.UlidFactory}.
 *                        Monotonic ordering within a single millisecond is guaranteed by
 *                        UlidFactory's increment-on-same-ms behavior. Never {@code null}.
 * @param eventType       dotted category key identifying the event's type per the taxonomy
 *                        (Doc 01 §4.3). Core types use underscored names (e.g.,
 *                        {@code state_reported}). Integration types use dotted namespace
 *                        ({@code {integration}.{type}}). Never {@code null} or blank.
 * @param schemaVersion   positive integer identifying the payload schema version. Starts
 *                        at 1 for the initial schema. Used by the upcaster pipeline
 *                        (Doc 01 §3.10) to chain transformations from older versions to
 *                        the current version. Always {@code >= 1}.
 * @param ingestTime      system clock timestamp at the moment the event was appended to the
 *                        log. Always present and system-derived — never sourced from an
 *                        external device. Stored as integer microseconds since epoch in
 *                        SQLite; serialized as ISO 8601 on the wire (LTD-08). Never
 *                        {@code null}.
 * @param eventTime       when the real-world occurrence happened, as reported by the event
 *                        source. {@code null} if the source has no reliable clock (e.g.,
 *                        some Zigbee devices). Same three-layer representation as
 *                        {@code ingestTime}: microseconds in storage, ISO 8601 on wire,
 *                        {@link Instant} in Java.
 * @param subjectRef      identifies the domain object this event is about — entity, device,
 *                        automation, person, or system component. The subject reference
 *                        pairs a ULID with a {@link SubjectType} discriminator for
 *                        efficient bus-side filtering. Never {@code null}.
 * @param subjectSequence monotonically increasing sequence number within the subject's
 *                        event stream. The pair ({@code subjectRef}, {@code subjectSequence})
 *                        forms a unique constraint used for optimistic concurrency control.
 *                        Always {@code >= 1}.
 * @param globalPosition  SQLite {@code rowid} — a monotonically increasing position across
 *                        all subjects. Subscribers checkpoint against this value to resume
 *                        processing after restart. Always {@code >= 0}; a value of 0 may
 *                        indicate pre-persistence state.
 * @param priority        delivery urgency and retention tier ({@link EventPriority#CRITICAL},
 *                        {@link EventPriority#NORMAL}, {@link EventPriority#DIAGNOSTIC}).
 *                        Affects subscriber delivery order and retention policy but does not
 *                        affect append-time durability. Never {@code null}.
 * @param origin          evidence-based classification of the event's source (e.g.,
 *                        {@link EventOrigin#PHYSICAL}, {@link EventOrigin#USER_COMMAND},
 *                        {@link EventOrigin#AUTOMATION}). {@link EventOrigin#UNKNOWN} is the
 *                        default when evidence is insufficient. Never {@code null}.
 * @param categories      consent-scope categories for this event, populated by static lookup
 *                        from {@code eventType} at creation time. Enables scoped access
 *                        controls, crypto-shredding (INV-PD-07), and subscription filtering.
 *                        Never {@code null} or empty. Defensively copied to guarantee
 *                        immutability.
 * @param causalContext    carries correlation, causation, and actor attribution for this
 *                        event in the causal chain. See {@link CausalContext} for root vs.
 *                        derived event semantics. Never {@code null}.
 * @param payload         the event-type-specific data. Structure varies by
 *                        ({@code eventType}, {@code schemaVersion}). Use pattern matching
 *                        on {@link DomainEvent} subtypes for type-safe dispatch. Never
 *                        {@code null}.
 * @see EventId
 * @see SubjectRef
 * @see CausalContext
 * @see DomainEvent
 */
public record EventEnvelope(
        EventId eventId,
        String eventType,
        int schemaVersion,
        Instant ingestTime,
        Instant eventTime,
        SubjectRef subjectRef,
        long subjectSequence,
        long globalPosition,
        EventPriority priority,
        EventOrigin origin,
        List<EventCategory> categories,
        CausalContext causalContext,
        DomainEvent payload
) {

    /**
     * Validates all envelope fields according to their documented constraints.
     *
     * <p>The {@code categories} list is defensively copied via {@link List#copyOf(java.util.Collection)}
     * to prevent external mutation after construction.</p>
     *
     * @throws NullPointerException     if any non-nullable field is {@code null}
     * @throws IllegalArgumentException if {@code eventType} is blank,
     *                                  {@code schemaVersion} is less than 1,
     *                                  {@code subjectSequence} is less than 1,
     *                                  {@code globalPosition} is negative, or
     *                                  {@code categories} is empty
     */
    public EventEnvelope {
        Objects.requireNonNull(eventId, "eventId must not be null");
        Objects.requireNonNull(eventType, "eventType must not be null");
        Objects.requireNonNull(ingestTime, "ingestTime must not be null");
        Objects.requireNonNull(subjectRef, "subjectRef must not be null");
        Objects.requireNonNull(priority, "priority must not be null");
        Objects.requireNonNull(origin, "origin must not be null");
        Objects.requireNonNull(categories, "categories must not be null");
        Objects.requireNonNull(causalContext, "causalContext must not be null");
        Objects.requireNonNull(payload, "payload must not be null");

        if (eventType.isBlank()) {
            throw new IllegalArgumentException("eventType must not be blank");
        }
        if (schemaVersion < 1) {
            throw new IllegalArgumentException(
                    "schemaVersion must be >= 1, got " + schemaVersion);
        }
        if (subjectSequence < 1) {
            throw new IllegalArgumentException(
                    "subjectSequence must be >= 1, got " + subjectSequence);
        }
        if (globalPosition < 0) {
            throw new IllegalArgumentException(
                    "globalPosition must be >= 0, got " + globalPosition);
        }

        categories = List.copyOf(categories);
        if (categories.isEmpty()) {
            throw new IllegalArgumentException("categories must not be empty");
        }
    }
}
