/*
 * HomeSynapse Core
 * Copyright (c) 2026 NexSys. All rights reserved.
 */

package com.homesynapse.event;

import java.util.Objects;

import com.homesynapse.platform.identity.Ulid;

/**
 * Globally unique, monotonically increasing identifier for each event in the domain
 * event store (Doc 01 §4.1).
 *
 * <p>An {@code EventId} is generated by the {@code EventPublisher} at append time using
 * {@link com.homesynapse.platform.identity.UlidFactory}. The ULID's embedded timestamp
 * and UlidFactory's increment-on-same-millisecond behavior guarantee that event IDs are
 * monotonically ordered within a single process, even when multiple events are appended
 * within the same millisecond.</p>
 *
 * <p>The event ID serves dual roles in the causal chain: for root events it is used as the
 * {@code correlation_id} (self-correlation), and for derived events the causing event's
 * {@code EventId} becomes the {@code causation_id} of the new event.</p>
 *
 * <p>The wrapped value is a {@link Ulid} per LTD-04. Stored as {@code BLOB(16)} in SQLite.</p>
 *
 * @param value the ULID identifying this event, never {@code null}
 * @see CausalContext
 */
public record EventId(Ulid value) implements Comparable<EventId> {

    /**
     * Validates that the ULID value is non-null.
     *
     * @throws NullPointerException if {@code value} is {@code null}
     */
    public EventId {
        Objects.requireNonNull(value, "EventId value must not be null");
    }

    /**
     * Creates an {@code EventId} from the given ULID.
     *
     * @param value the ULID, never {@code null}
     * @return a new {@code EventId} instance
     * @throws NullPointerException if {@code value} is {@code null}
     */
    public static EventId of(Ulid value) {
        return new EventId(value);
    }

    /**
     * Creates an {@code EventId} by parsing a 26-character Crockford Base32 ULID string.
     *
     * @param crockford the Crockford Base32 encoded ULID, never {@code null}
     * @return a new {@code EventId} instance
     * @throws NullPointerException     if {@code crockford} is {@code null}
     * @throws IllegalArgumentException if {@code crockford} is not a valid ULID string
     */
    public static EventId parse(String crockford) {
        return new EventId(Ulid.parse(crockford));
    }

    @Override
    public int compareTo(EventId other) {
        return value.compareTo(other.value);
    }

    @Override
    public String toString() {
        return value.toString();
    }
}
